cpu/coretexm_common: Issue ibs after setting stack pointer
RIOT-OS/RIOT pull request #15086
Opened 2020-09-25 10:00 UTC by maribu

### Contribution description

Citing https://developer.arm.com/documentation/dui0552/a/the-cortex-m3-processor/programmers-model/core-registers?lang=en

> When changing the stack pointer, software must use an ISB instruction immediately after the MSR instruction. This ensures that instructions after the ISB instruction execute using the new stack pointer. See ISB

This apparently also applies not only to Cortex M3, as this fixes https://github.com/RIOT-OS/RIOT/issues/15085

@kaspar030: Thanks for pointing out the fix.

### Testing procedure

See "steps to reproduce" in https://github.com/RIOT-OS/RIOT/issues/15085

### Issues/PRs references

Fixes https://github.com/RIOT-OS/RIOT/issues/15085

2020-09-25 11:14 UTC, kaspar030 requested changes

2020-09-25 11:14 UTC, kaspar030 commented on cpu/cortexm_common/thread_arch.c
> +    "ibs                              \n" /* flush pipeline */
I think this is only necessary when using msr, not by writing to sp in general. (gcc generates tons of sp modifying code in the function prologues, I've not seen a pipeline flush in there).

2020-09-25 11:14 UTC, kaspar030 commented on cpu/cortexm_common/thread_arch.c
> +    "ibs                              \n" /* flush pipeline */
not needed, see other comment

2020-09-25 11:14 UTC, kaspar030 commented on cpu/cortexm_common/thread_arch.c
> +    "ibs                              \n" /* flush pipeline */
here I'm not sure. the write to sp doesn't need this, the msr instruction above might. but as the psp is only used after exception return, I don't think it is really needed.

2020-09-25 11:16 UTC, kaspar030 commented
>  this fixes #15085

but, the __dsb() is the fix for #15085, right? (I don't think they should be in the same PR)

2020-09-25 12:00 UTC, maribu commented
> but, the __dsb() is the fix for #15085, right?

Yes. But I think it should have been an ISB there as well, at least according to some guy in the internet. I can confirm that the issue is seemingly gone with ISB as well.

> (I don't think they should be in the same PR)

Dropped the other isb

2020-09-25 12:06 UTC, kaspar030 approved these changes
ACK.

While I'm not sure this is necessary for Cortex-M0, and I'm not sure it is necessary if thread_yield_higher() is a regular function on M3/M4, I'm willing to accept the extra instruction just to avoid surprises when inlining or using LTO.

And it certainly fixes issues on M7.

2020-09-25 13:47 UTC, maribu commented
Ignoring all ESP failures, the following tests failed:

- [tests/pkg_libhydrogen](https://ci.riot-os.org/RIOT-OS/RIOT/15086/49f3d1056d7e7a973edf8125f82232a4576588c6/output/run_test/tests/pkg_libhydrogen/samr21-xpro:llvm.txt) on `samr21-xpro` when compiled with LLVM
- [tests/pkg_utensor](https://ci.riot-os.org/RIOT-OS/RIOT/15086/49f3d1056d7e7a973edf8125f82232a4576588c6/output/run_test/tests/pkg_utensor/samr21-xpro:llvm.txt) with `samre-xpro` when compiled with LLVM
- [tests/pkg_lvgl](https://ci.riot-os.org/RIOT-OS/RIOT/15086/49f3d1056d7e7a973edf8125f82232a4576588c6/output/compile/tests/pkg_lvgl/wemos-zero:gnu.txt) on `wemos-zero` when compiled with GCC

I can investigate the last one, but I have not ~~Atmel~~Microchip Xpro at hand. (I consider them too expensive...)

2020-09-25 13:53 UTC, aabadie commented
> tests/pkg_utensor with samre-xpro when compiled with LLVM

This one should be fixed by #15089

2020-09-25 14:10 UTC, maribu commented
>     * [tests/pkg_lvgl](https://ci.riot-os.org/RIOT-OS/RIOT/15086/49f3d1056d7e7a973edf8125f82232a4576588c6/output/compile/tests/pkg_lvgl/wemos-zero:gnu.txt) on `wemos-zero` when compiled with GCC

Here the culprit are connectivity issues on the worker, cloning `lvgl` failed.

Nice to know that the board files are indeed used :-)

2020-09-25 14:20 UTC, maribu commented
On my `wemos-zero` (`samd21`, not `samr21`), `tests/pkg_libhydrogen` is working. Maybe that was just a glitch?

2020-09-25 14:50 UTC, bergzand commented
> On my `wemos-zero` (`samd21`, not `samr21`), `tests/pkg_libhydrogen` is working. Maybe that was just a glitch?

It's not working on my samr21-xpro: https://github.com/RIOT-OS/RIOT/issues/15066 :cry:

2020-09-25 14:51 UTC, bergzand commented
But it is unrelated to this PR

2020-09-25 14:57 UTC, maribu commented
OK, with all tests failures due to other reasons, I'll rerun murdock without tests.

I wonder if in such a situation I would be allowed to disable compile checks (as those have passed an hour ago already).

2020-09-25 15:00 UTC, aabadie commented
> I would be allowed to disable compile checks

Even if it's not a super nice practice, some people already do that in such situations, to save a bit of CPU time.

2020-09-26 12:39 UTC, maribu commented
All green :-)

2020-09-26 19:05 UTC, merged

2020-09-28 07:36 UTC, maribu commented
Thanks :-)