dist/tools/suit: convert to package
RIOT-OS/RIOT pull request #15095
Opened 2020-09-26 12:08 UTC by benpicco

### Contribution description

Fetch the suit-manifest-generator from upstream instead of keeping a copy in the RIOT repository.

### Testing procedure

All SUIT examples should still compile, manifests should be generated.

### Issues/PRs references

Can't test due to https://github.com/RIOT-OS/RIOT/pull/14436#issuecomment-699486825

2020-10-02 10:59 UTC, aabadie commented
needs rebase

2020-10-02 11:09 UTC, benpicco commented
I guess we could just patch the package to remove `pyhsslms`, we don't use it.
That way we don't have to wait for all the workers to get updated again.

2020-12-31 17:04 UTC, aabadie requested changes
I have a few comments. The build system integration can be improved.

2020-12-31 17:04 UTC, aabadie commented on dist/tools/suit/Makefile
> +	-$(Q)ln -s $(PKGDIRBASE)/suit-manifest-generator .
This looks ugly. You could either change the value of `SUIT_TOOL` defined in

https://github.com/RIOT-OS/RIOT/blob/453d0478dce107f810f4690093899e36faaf7cb8/makefiles/suit.base.inc.mk#L2-L3

to `$(PKGDIRBASE)/suit-manifest-generator/bin/suit-tool`

Or specify `PKG_SOURCE_DIR` before the include of `pkg.mk`:

```mk
PKG_SOURCE_DIR ?= $(CURDIR)
include $(RIOTBASE)/pkg/pkg.mk
```
Both options are untested but I think they are better than the current symlink approach.

In any case:
```suggestion
	:
```

2021-01-05 13:28 UTC, aabadie commented
Needs a rebase

2021-01-05 17:01 UTC, benpicco commented
Unfortunately `tests/suit_manifest` still fails with

```
--- testing manifest 0
Unable to parse COSE signature
---- res=-1 (expected=-6)
```

maybe @bergzand still knows how our version of this tool differs from upstream?

2022-01-20 14:46 UTC, fjmolinas commented
Does this still fail?

2022-01-20 16:07 UTC, benpicco commented
I don't see why it would not, upstream didn't change.

2022-04-17 06:03 UTC, closed without merging