Makefile.include: discover object files in sub-paths while linking
RIOT-OS/RIOT pull request #15364
Opened 2020-11-03 09:07 UTC by leandrolanzieri

### Contribution description
The `find` command that collects the object files while linking is currently too strict and does not include sub-directories within the module's directories. This causes use cases like the described in #15357 to fail. This allows a recursive search for object files in those directories.

I've tested this following the steps in #15357 and now it works properly.

### Testing procedure
- Green murdock
- The issue described in #15357 should be fixed with this.

### Issues/PRs references
Fixes #15357
Issue introduced in #14754

2020-11-03 09:17 UTC, larseggert approved these changes
Fixes the issue

2020-11-03 09:18 UTC, cgundogan approved these changes
Change is sensible.  Tested as outlined in the PR description and works for me.  @larseggert  does the proposed change also work for you? (maybe also for other test cases, if there are any?)

2020-11-03 09:19 UTC, cgundogan commented
>Fixes the issue

I was too slow (:

2020-11-03 16:17 UTC, cgundogan requested changes
`find` returns another order of object files for linking.  This yields a random offset for symbols in the elf file.  By sorting the output of sort, the elf file generation should be deterministic and the hash compare test should succeed.

2020-11-03 16:17 UTC, cgundogan commented on Makefile.include
> +  _LINK = $(if $(CPPMIX),$(LINKXX),$(LINK)) $$(find $(BASELIBS:%.module=$(BINDIR)/%/) -name "*.o" 2> /dev/null) $(ARCHIVES_GROUP) $(LINKFLAGS) $(LINKFLAGPREFIX)-no_pie
```suggestion
  _LINK = $(if $(CPPMIX),$(LINKXX),$(LINK)) $$(find $(BASELIBS:%.module=$(BINDIR)/%/) -name "*.o" 2> /dev/null | sort) $(ARCHIVES_GROUP) $(LINKFLAGS) $(LINKFLAGPREFIX)-no_pie
```

2020-11-03 16:17 UTC, cgundogan commented on Makefile.include
> +  _LINK = $(if $(CPPMIX),$(LINKXX),$(LINK)) $$(find $(BASELIBS:%.module=$(BINDIR)/%/) -name "*.o" 2> /dev/null) $(ARCHIVES_GROUP) $(LINKFLAGS) $(LINKFLAGPREFIX)-Map=$(BINDIR)/$(APPLICATION).map
```suggestion
  _LINK = $(if $(CPPMIX),$(LINKXX),$(LINK)) $$(find $(BASELIBS:%.module=$(BINDIR)/%/) -name "*.o" 2> /dev/null | sort) $(ARCHIVES_GROUP) $(LINKFLAGS) $(LINKFLAGPREFIX)-Map=$(BINDIR)/$(APPLICATION).map
```

2020-11-03 16:20 UTC, cgundogan commented
you can squash the suggestions directly

2020-11-04 08:09 UTC, cgundogan approved these changes
ACK. Murdock is also green @bergzand should this be backported?

2020-11-04 08:10 UTC, merged