sock/dtls: add getter/setter for the remote UDP endpoint of sock_dtls_session_t
RIOT-OS/RIOT pull request #15690
Opened 2020-12-21 17:05 UTC by janosbrodbeck

### Contribution description
This PR adds two new functions to the DTLS sock API: `sock_dtls_session_get_udp_ep()` and `sock_dtls_session_set_udp_ep()`.
Those functions add the ability to add or get the remote UDP endpoint from a session object (`sock_dtls_session_t`). 

__Necessity of the setter:__
When using `sock_dtls_session_init()` to initiate a handshake there is no need to set the remote endpoint because the function has the endpoint as parameter and sets the endpoint itself. But there is another legitimate way to initiate a handshake: by using `sock_dtls_send()`/`sock_dtls_send_aux()`. 

These functions start a handshake when no session exists and the timeout is > 0. But for that the endpoint needs to be set since it is not done by the function (since there is no endpoint parameter and it would not make sense to add it to that function).

From the documentation: 
```
timeout             Handshake timeout in microseconds.
 *                      If `timeout > 0`, will start a new handshake if no
 *                      session exists yet. The function will block until
 *                      handshake completed or timed out.
```

### Testing procedure
Implementation in tinyDTLS can be tested with the test [pkg_tinydtls_sock_async](https://github.com/RIOT-OS/RIOT/tree/master/tests/pkg_tinydtls_sock_async) together with this patch:
```
diff --git a/tests/pkg_tinydtls_sock_async/dtls-client.c b/tests/pkg_tinydtls_sock_async/dtls-client.c
index 2aefc75856..b03ac19ed7 100644
--- a/tests/pkg_tinydtls_sock_async/dtls-client.c
+++ b/tests/pkg_tinydtls_sock_async/dtls-client.c
@@ -200,6 +200,22 @@ static int client_send(char *addr_str, char *data)
         return -1;
     }
 
+    sock_dtls_session_t test_session;
+    sock_dtls_session_set_udp_ep(&test_session, &remote);
+
+    sock_udp_ep_t test_ep;
+    sock_dtls_session_get_udp_ep(&test_session, &test_ep);
+
+    printf("\n\nAddress: ");
+    for (uint8_t i=0; i < sizeof(ipv6_addr_t); i++) {
+        printf("%02x:", test_ep.addr.ipv6[i]);
+    }
+    puts("");
+    printf("Port: %d\n", test_ep.port);
+    printf("Family: %d\n", test_ep.family);
+    printf("Interface: %d\n", test_ep.netif);
+    puts("\n");
+
     if (sock_dtls_create(&_dtls_sock, &_udp_sock,
                          SOCK_DTLS_CLIENT_TAG,
                          SOCK_DTLS_1_2, SOCK_DTLS_CLIENT) < 0) {

```

To run it: 
* Flash and run on one device (e.g. native)
* Execute `dtlsc {ip} {some data}`
The printed UDP endpoint should be the valid remote endpoint. (Send fails because we have no server device)

### Issues/PRs references
Fixes #15615

2020-12-21 17:21 UTC, janosbrodbeck commented
Could someone please link this PR to the issue #15615? When this is done everything from the issue should be addressed.

2020-12-22 04:39 UTC, pokgak commented
Would it make sense to also replace `_session_to_ep` and `_ep_to_session` with these functions too because they are doing the same thing?

2020-12-22 10:17 UTC, miri64 commented
> Could someone please link this PR to the issue #15615? When this is done everything from the issue should be addressed.

Done. As described in the template, you need to use the right wording for Github to recognize it. I changed your issue reference to "Fixes #15615" in op :-).

2020-12-22 10:19 UTC, miri64 commented on sys/include/net/sock/dtls.h
> + *       @ref sock_dtls_send() to set the remote endpoint.
Maybe add some example usage code here?

2020-12-22 11:12 UTC, janosbrodbeck commented
> Would it make sense to also replace `_session_to_ep` and `_ep_to_session` with these functions too because they are doing the same thing?

True. And we can also tick ` Add general way to set/get sock_dtls_session_t from a sock_udp_ep_t and vice-versa` in #10897 if this is done.

I'll add a commit to replace this helper functions.

2020-12-30 15:26 UTC, janosbrodbeck commented
> Maybe add some example usage code here?

An example doesn't really fit there in my opinion. I've added an exemplary usage of blocking `sock_dtls_send()` to the note section of the two send functions. Theoretically you could have also put it to `sock_dtls_session_init()` as well. 
Is that sufficient/fitting for you?

> Would it make sense to also replace _session_to_ep and _ep_to_session with these functions too because they are doing the same thing?

I've looked at it again and...I don't think it is worth the hassle. Some functions call the helper functions without having a `sock_dtls_session_t` object. E.g. the `_write()` function. If I would remove the helper function I would have to add a `sock_dtls_session_t` object at these spots just to call the new functions instead.

2021-01-04 11:38 UTC, miri64 requested changes

2021-01-04 11:38 UTC, miri64 commented on sys/include/net/sock/dtls.h
> + *          An exemplary send with a blocking handshake is:
```suggestion
An example for a blocking handshake is:
```

2021-01-04 11:38 UTC, miri64 commented on sys/include/net/sock/dtls.h
> + *          An exemplary send with a blocking handshake is:
Here too.

2021-01-04 11:38 UTC, miri64 commented on sys/include/net/sock/dtls.h
> + *          An exemplary send with a blocking handshake is:
I think that example is enough to be mentioned once in `sock_dtls_send()` btw.

2021-01-04 11:40 UTC, miri64 commented on pkg/tinydtls/contrib/sock_dtls.c
> +    _session_to_ep(&session->dtls_session, ep);
Would it make sense to replace the calls of this function with `sock_dtls_session_get_udp_ep()` in general?

2021-01-04 16:02 UTC, janosbrodbeck commented
Applied the change request and removed the example from the `sock_dtls_send_aux()`.

2021-01-04 19:25 UTC, janosbrodbeck commented
Squashed.

2021-01-05 13:20 UTC, miri64 approved these changes
Tested as suggested and it works :-). ACK!

2021-01-05 13:23 UTC, merged