ztimer: add ztimer_is_set() to user API
RIOT-OS/RIOT pull request #15780
Opened 2021-01-15 13:48 UTC by haukepetersen

### Contribution description
To improve the low power support I am currently porting NimBLE to use `ztimer` as RIOT timer backend. Mapping the `ztimer` API works mostly flawless, the only thing missing is a `is_set()` function. The current implementation uses an ugly hack by using xtimer internal struct members to do this check -> so for the improved port I'd like to have this less error prone :-)

This PR simply exposes `ztimer`s internal `_is_set()` function by wrapping it into a critical section inside a newly added `ztimer_is_set()` user API function. Should be pretty straight forward.

### Testing procedure
I added a call to the new `ztimer_is_set()` function in `tests/ztimer_periodic`. So simply run `tests/ztimer_periodic` on any platform -> it should succeed as expected.

### Issues/PRs references
none

2021-01-15 21:12 UTC, kaspar030 requested changes
LGTM.

Please fix the uncrustify suggestion, ztimer is no-discission uncrustify (like core). You can squash it in directly.

2021-01-15 21:13 UTC, kaspar030 commented
> This PR simply exposes `ztimer`s internal `_is_set()` function by wrapping it into a critical section inside a newly added `ztimer_is_set()` user API function. Should be pretty straight forward.

I didn't expose it because it feels a bit dangerous to say "false" if the wrong clock is parsed. On the other hand, I didn't want to add an extra "clock" field to ztimer_t just to be able to remove the clock parameter from is_set()...

2021-01-18 16:51 UTC, haukepetersen commented
fixed (and squashed) uncrustify issue

2021-01-20 11:42 UTC, kaspar030 approved these changes
ACK.

2021-01-20 11:42 UTC, merged