cpu/stm32/rtc: add unlock/lock to rtc_clear_alarm
RIOT-OS/RIOT pull request #15796
Opened 2021-01-19 12:36 UTC by fjmolinas

### Contribution description

#15628 (because a `rtc_clear_alarm` call was added to the test) exposed a bug on `stm32/rtc` where the RTC was not `locked`/`unlocked` when calling `rtc_clear_alarm`. This caused `tests/periph_rtc` to hang at least on `nucleo-f207zg`.

### Testing procedure

`BOARD=nucleo-f207zg make -C tests/periph_rtc flash test -j3`

```
main(): This is RIOT! (Version: 2021.04-devel-66-g7c12e-pr_rtc_lock_unlock)

RIOT RTC low-level driver test
This test will display 'Alarm!' every 2 seconds for 4 times
  Setting clock to   2020-02-28 23:59:57
Clock value is now   2020-02-28 23:59:57
  Setting alarm to   2020-02-28 23:59:59
   Alarm is set to   2020-02-28 23:59:59
  Alarm cleared at   2020-02-28 23:59:57
       No alarm at   2020-02-28 23:59:59
  Setting alarm to   2020-02-29 00:00:01

Alarm!
Alarm!
Alarm!
Alarm!
```

2021-01-19 12:53 UTC, benpicco approved these changes
looks good to me

2021-01-19 15:09 UTC, aabadie requested changes
Blocking because I'd like to test on several STM32 families before merging, and it's already approved (without ACK btw), so mergeable.

2021-01-19 15:48 UTC, fjmolinas commented
Here are test results on all but `stm32f0`:

https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/212/artifact/

There was a compilation issue because of concurrency for `nucleo-f334r8`.

2021-01-19 15:48 UTC, fjmolinas commented
> Here are test results on all but `stm32f0`:
> 
> https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/212/artifact/
> 
> There was a compilation issue because of concurrency for `nucleo-f334r8`.

Actually no stm32G* either

2021-01-19 16:27 UTC, aabadie commented
Tested on stm32g4 (there's no RTC on G0):

<details>

```
make BOARD=nucleo-g431rb -C tests/periph_rtc/ flash test
make: Entering directory '/work/riot/RIOT/tests/periph_rtc'
Building application "tests_periph_rtc" for "nucleo-g431rb" with MCU "stm32".

"make" -C /work/riot/RIOT/boards/nucleo-g431rb
"make" -C /work/riot/RIOT/boards/common/nucleo
"make" -C /work/riot/RIOT/core
"make" -C /work/riot/RIOT/cpu/stm32
"make" -C /work/riot/RIOT/cpu/cortexm_common
"make" -C /work/riot/RIOT/cpu/cortexm_common/periph
"make" -C /work/riot/RIOT/cpu/stm32/periph
"make" -C /work/riot/RIOT/cpu/stm32/stmclk
"make" -C /work/riot/RIOT/cpu/stm32/vectors
"make" -C /work/riot/RIOT/drivers
"make" -C /work/riot/RIOT/drivers/periph_common
"make" -C /work/riot/RIOT/sys
"make" -C /work/riot/RIOT/sys/auto_init
"make" -C /work/riot/RIOT/sys/div
"make" -C /work/riot/RIOT/sys/isrpipe
"make" -C /work/riot/RIOT/sys/malloc_thread_safe
"make" -C /work/riot/RIOT/sys/newlib_syscalls_default
"make" -C /work/riot/RIOT/sys/pm_layered
"make" -C /work/riot/RIOT/sys/stdio_uart
"make" -C /work/riot/RIOT/sys/test_utils/interactive_sync
"make" -C /work/riot/RIOT/sys/tsrb
"make" -C /work/riot/RIOT/sys/xtimer
   text	   data	    bss	    dec	    hex	filename
  13712	    132	   2420	  16264	   3f88	/work/riot/RIOT/tests/periph_rtc/bin/nucleo-g431rb/tests_periph_rtc.elf
/work/riot/RIOT/dist/tools/openocd/openocd.sh flash /work/riot/RIOT/tests/periph_rtc/bin/nucleo-g431rb/tests_periph_rtc.elf
### Flashing Target ###
Open On-Chip Debugger 0.10.0+dev-01406-gca211373d-dirty (2020-10-26-22:35)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
srst_only separate srst_nogate srst_open_drain connect_assert_srst

Info : clock speed 2000 kHz
Info : STLINK V3J2M1 (API v3) VID:PID 0483:374E
Info : Target voltage: 3.327528
Info : stm32g4x.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : starting gdb server for stm32g4x.cpu on 0
Info : Listening on port 45519 for gdb connections
    TargetName         Type       Endian TapName            State       
--  ------------------ ---------- ------ ------------------ ------------
 0* stm32g4x.cpu       hla_target little stm32g4x.cpu       reset

Info : Unable to match requested speed 2000 kHz, using 1000 kHz
Info : Unable to match requested speed 2000 kHz, using 1000 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0800096c msp: 0x20000200
Info : device idcode = 0x20016468 (STM32G43/G44xx - Rev: Z)
Info : flash size = 128kbytes
Info : flash mode : single-bank
Info : Padding image section 1 at 0x08003614 with 4 bytes (bank write end alignment)
Warn : Adding extra erase range, 0x08003618 .. 0x080037ff
auto erase enabled
wrote 13848 bytes from file /work/riot/RIOT/tests/periph_rtc/bin/nucleo-g431rb/tests_periph_rtc.elf in 0.529240s (25.553 KiB/s)

verified 13844 bytes in 0.177126s (76.327 KiB/s)

Info : Unable to match requested speed 2000 kHz, using 1000 kHz
Info : Unable to match requested speed 2000 kHz, using 1000 kHz
shutdown command invoked
Done flashing
r
/work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --no-reconnect --noprefix --no-repeat-command-on-empty-line 
Twisted not available, please install it if you want to use pyterm's JSON capabilities
Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
READY
s
START
main(): This is RIOT! (Version: 2021.04-devel-66-g7c12e-review_stm32_rtc)

RIOT RTC low-level driver test
This test will display 'Alarm!' every 2 seconds for 4 times
  Setting clock to   2020-02-28 23:59:57
Clock value is now   2020-02-28 23:59:57
  Setting alarm to   2020-02-28 23:59:59
   Alarm is set to   2020-02-28 23:59:59
  Alarm cleared at   2020-02-28 23:59:57
       No alarm at   2020-02-28 23:59:59
  Setting alarm to   2020-02-29 00:00:01

Alarm!
Alarm!
Alarm!
Alarm!
```

</details>

2021-01-19 16:28 UTC, aabadie approved these changes
ACK

2021-01-19 16:29 UTC, merged

2021-01-20 09:29 UTC, fjmolinas commented
Backport provided in #15811