driver/sgp30: initial import
RIOT-OS/RIOT pull request #16222
Opened 2021-03-23 22:02 UTC by fjmolinas

### Contribution description

This PR adds initial support for the [sensirion SGP30](https://www.mouser.com/pdfdocs/Sensirion_Gas_Sensors_SGP30_Datasheet_EN-1148053.pdf) gas sensor. This sensor outputs air quality readings for eCO2 and TVOC. These can be compensated according to the absolute humidity as well The algorithm baseline values can also dynamically be changed, see [here](https://files.seeedstudio.com/wiki/Grove-VOC_and_eCO2_Gas_Sensor-SGP30/res/Sensirion_Gas_Sensors_SGP30_Driver-Integration-Guide_HW_I2C.pdf) for a possible approach (currently left to the application to optionally implement as it needs persistent storage).

### Testing procedure

- run basic test `make -C tests/driver_sgp30/ flash term`

```
2021-03-23 23:02:01,756 # eCO2 [ppm]: 403
2021-03-23 23:02:01,760 # +-------------------------------------+
2021-03-23 23:02:01,875 # TVOC [ppb]: 4
2021-03-23 23:02:01,877 # eCO2 [ppm]: 402
2021-03-23 23:02:01,880 # +-------------------------------------+
2021-03-23 23:02:01,995 # TVOC [ppb]: 5
2021-03-23 23:02:01,997 # eCO2 [ppm]: 401
2021-03-23 23:02:02,000 # +-------------------------------------+
2021-03-23 23:02:02,115 # TVOC [ppb]: 2
2021-03-23 23:02:02,117 # eCO2 [ppm]: 408
2021-03-23 23:02:02,120 # +-------------------------------------+
```

- test with saul

```
2021-03-23 23:00:25,347 # ##########################
2021-03-23 23:00:26,305 #
2021-03-23 23:00:26,308 # Dev: LED(orange)      Type: ACT_SWITCH
2021-03-23 23:00:26,310 # Data:               0
2021-03-23 23:00:26,310 #
2021-03-23 23:00:26,313 # Dev: Button(SW0)      Type: SENSE_BTN
2021-03-23 23:00:26,315 # Data:               0
2021-03-23 23:00:26,329 #
2021-03-23 23:00:26,331 # Dev: sgp30    Type: SENSE_CO2
2021-03-23 23:00:26,333 # Data:             757 ppm
2021-03-23 23:00:26,347 #
2021-03-23 23:00:26,349 # Dev: sgp30    Type: SENSE_TVOC
2021-03-23 23:00:26,351 # Data:             999 ppb
2021-03-23 23:00:26,352 #
2021-03-23 23:00:26,354 # ##########################
```

### Issues/PRs references

2021-04-07 07:33 UTC, kaspar030 commented on drivers/include/sgp30.h
> +    bool ready;                 /**< if initialization faze is over*/
```suggestion
    bool ready;                 /**< if initialization phase is over*/
```

I think faze means about the opposite ;)

2021-04-07 07:42 UTC, bergzand reviewed
Some initial nitpicks!

2021-04-07 07:42 UTC, bergzand commented on drivers/include/sgp30.h
> + *
Duplicate newline

2021-04-07 07:42 UTC, bergzand commented on drivers/include/sgp30.h
> + *
And another

2021-04-07 07:42 UTC, bergzand commented on drivers/include/sgp30.h
> + *
Another one :(

2021-04-07 07:53 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +                       size_t len, uint32_t delay, bool read)
please rename `read`, maybe `do_read`?

2021-04-07 08:00 UTC, fjmolinas commented on drivers/sgp30/include/sgp30_constants.h
> +#define SGP30_MINIMUM_SAMPLING_PERIOD        (1 * US_PER_SEC)
```suggestion
#define SGP30_RECOMMENDED_SAMPLING_PERIOD        (1 * US_PER_SEC)
```

2021-04-07 08:01 UTC, fjmolinas commented on drivers/sgp30/sgp30.c
> +#define SGP30_DELAY_MEASURE_RAW_SIGNALS     (25 * MS_PER_SEC)
All these should be `US_PER_MS`.

2021-04-07 08:06 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> + * @name      Max delays for SGP30 I2C commands completion
It looks like this needs mostly milliseconds, can the driver be made to only use ZTIMER_MSEC?

2021-04-07 08:07 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +#define SGP30_DELAY_READ_SERIAL             (500)
hm, using one ms here might be too long

2021-04-07 08:07 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> + * @name      Max delays for SGP30 I2C commands completion
hey, let's do this as follow up, it would be an optimization anyways

2021-04-07 08:10 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +    if (a_humidity > 256000) {
```suggestion
    if (a_humidity > 256000LU) {
```

2021-04-07 08:17 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +    if (_crc8(frame, 2) != frame[2] || _crc8(frame + 3, 2) != frame[5]) {
I've seen this at least two times. maybe factor out a function that does the equivalent of `_crc8(buf, 2) == buf[2]`, then one using that for a full 6 byte frame (`_crc8_matches(frame) && _crc8_matches(frame + 3)`)?

2021-04-07 08:18 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +    uint8_t frame_cmd[sizeof(cmd) + len];
(style, feel free to ignore)
```suggestion
    uint8_t frame_cmd[sizeof(cmd) + len] = { cmd >> 8, cmd & 0xFF };
```

2021-04-07 08:20 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +            DEBUG_PUTS("[sgp30]: fail to write data");
```suggestion
            DEBUG_PUTS("[sgp30]: failed to write data");
```

2021-04-07 08:24 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +    uint8_t frame[3];
here and below would benefit for a setter (`_set(uint8_t *buf, uint16_t val) { buf[0] = val >> 8; buf[1] = val & 0xFF; buf[3] = _crc8(...);}`.

2021-04-07 08:24 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +    frame[0] = data->eco2 >> 8;
could reuse setter here

2021-04-07 08:25 UTC, kaspar030 commented on tests/driver_sgp30/main.c
> +        ztimer_sleep(ZTIMER_USEC, 100000);
```suggestion
        ztimer_sleep(ZTIMER_USEC, 100000LU);
```

2021-04-07 09:28 UTC, fjmolinas commented
@kaspar030 I think I addressed your comments.

2021-04-07 11:36 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +    /* start air quality measurement_get_uint16_and_check_crc(&frame[0], &buf[0]) */
```suggestion
    /* start air quality measurement */
```

2021-04-07 11:40 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +    if (_get_uint16_and_check_crc(&frame[0], (uint16_t *)&buf[4]) ||
this is now possibly causing alignment errors, we cannot cast any buf to `uint16_t`.

2021-04-07 11:42 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +    if (_get_uint16_and_check_crc(&frame[0], (uint16_t *)&buf[4]) ||
I suggest using a temp `uint16_t[3]` and memcpy'ing it.

2021-04-07 12:28 UTC, kaspar030 commented
@fjmolinas please fix those last issues, then squash. Would be great if you could post another test run, I don't have the sensor :(

2021-04-07 12:36 UTC, kaspar030 requested changes
last round of doc typos

2021-04-07 12:36 UTC, kaspar030 commented on drivers/include/sgp30.h
> + * intervals of 1s for best operation of the dynamic baseline compensationalgorithm.
```suggestion
 * intervals of 1s for best operation of the dynamic baseline compensation algorithm.
```

2021-04-07 12:36 UTC, kaspar030 commented on drivers/include/sgp30.h
> + * This above not done by default but if the `sgp30_strict` module is included then
```suggestion
 * The above not done by default but if the `sgp30_strict` module is included.
```

2021-04-07 12:36 UTC, kaspar030 commented on drivers/include/sgp30.h
> + * then if attempting to read before the is completed then -EAGAIN will be returned.
```suggestion
 * In that case, if attempting to read before the is completed, -EAGAIN will be returned.
```

2021-04-07 12:36 UTC, kaspar030 commented on drivers/include/sgp30.h
> + * signals. @ref sgp30_set_absolute_humidity can be used to change the
```suggestion
 * measurements. @ref sgp30_set_absolute_humidity can be used to change the
```

2021-04-07 12:36 UTC, kaspar030 commented on drivers/include/sgp30.h
> + * dynamic baseline compensation can be seen in at [SGP30 driver integration] (https://files.seeedstudio.com/wiki/Grove-VOC_and_eCO2_Gas_Sensor-SGP30/res/Sensirion_Gas_Sensors_SGP30_Driver-Integratio
```suggestion
 * dynamic baseline compensation can be seen at [SGP30 driver integration] (https://files.seeedstudio.com/wiki/Grove-VOC_and_eCO2_Gas_Sensor-SGP30/res/Sensirion_Gas_Sensors_SGP30_Driver-Integration-Guide_HW_I2C.pdf).
```

2021-04-07 12:36 UTC, kaspar030 commented on drivers/include/sgp30.h
> + * output relative humidity, this can be calculated it temperature is also
```suggestion
 * output relative humidity, this can be calculated if temperature is also
```

2021-04-07 12:36 UTC, kaspar030 commented on drivers/include/sgp30.h
> + * It returns the sensor raw signals which are used as inputs for
```suggestion
 * It returns the raw sensor signals which are used as inputs for
```

2021-04-07 12:36 UTC, kaspar030 commented on drivers/include/sgp30.h
> + * the  on-chip calibration and baseline compensationalgorithms.
```suggestion
 * the  on-chip calibration and baseline compensation algorithms.
```

2021-04-07 12:36 UTC, kaspar030 commented on drivers/saul/init_devs/auto_init_sgp30.c
> + * Copyright (C) 2018 Gunar Schorcht
```suggestion
 * Copyright (C) 2021 Inria
```

2021-04-07 12:36 UTC, kaspar030 commented on drivers/saul/init_devs/auto_init_sgp30.c
> + * @author      Gunar Schorcht <gunar@schorcht.net>
you?

2021-04-07 12:36 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +
newline

2021-04-07 12:36 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +
newline

2021-04-07 12:36 UTC, kaspar030 commented on drivers/sgp30/sgp30.c
> +                       size_t len, uint32_t delay, bool read)
still called `read`

2021-04-07 17:07 UTC, fjmolinas commented
@kaspar030 I hope I got everything this time, tested again:


- run basic test `make -C tests/driver_sgp30/ flash term`

```
2021-04-07 18:59:36,402 # Device is not yet ready
2021-04-07 18:59:36,505 # Device is not yet ready
2021-04-07 18:59:36,608 # Device is not yet ready
2021-04-07 18:59:36,710 # TVOC [ppb]: 0
2021-04-07 18:59:36,711 # eCO2 [ppm]: 400
2021-04-07 18:59:36,715 # +-------------------------------------+
2021-04-07 18:59:36,817 # TVOC [ppb]: 0
2021-04-07 18:59:36,818 # eCO2 [ppm]: 400
2021-04-07 18:59:36,822 # +-------------------------------------+
2021-04-07 18:59:36,924 # TVOC [ppb]: 0
2021-04-07 18:59:36,925 # eCO2 [ppm]: 400
2021-04-07 18:59:36,929 # +-------------------------------------+
...
2021-04-07 19:01:34,979 # +-------------------------------------+
2021-04-07 19:01:35,081 # TVOC [ppb]: 4
2021-04-07 19:01:35,083 # eCO2 [ppm]: 413
2021-04-07 19:01:35,086 # +-------------------------------------+
2021-04-07 19:01:35,188 # TVOC [ppb]: 4
2021-04-07 19:01:35,190 # eCO2 [ppm]: 413
2021-04-07 19:01:35,193 # +-------------------------------------+
2021-04-07 19:01:35,295 # TVOC [ppb]: 4
2021-04-07 19:01:35,297 # eCO2 [ppm]: 413
2021-04-07 19:01:35,300 # +-------------------------------------+
2021-04-07 19:01:35,402 # TVOC [ppb]: 4
2021-04-07 19:01:35,404 # eCO2 [ppm]: 413
2021-04-07 19:01:35,407 # +-------------------------------------+
2021-04-07 19:01:35,510 # TVOC [ppb]: 4
2021-04-07 19:01:35,511 # eCO2 [ppm]: 413
2021-04-07 19:01:35,514 # +-------------------------------------+
2021-04-07 19:01:35,617 # TVOC [ppb]: 4
2021-04-07 19:01:35,618 # eCO2 [ppm]: 413
2021-04-07 19:01:35,622 # +-------------------------------------+
```

- no strict mode `DISABLE_MODULE=sgp30_strict make -C tests/driver_sgp30/ flash term` (values change more often since there is no strict 1s sampling)

```
2021-04-07 19:02:44,357 # +-------------------------------------+
2021-04-07 19:02:44,472 # TVOC [ppb]: 0
2021-04-07 19:02:44,474 # eCO2 [ppm]: 404
2021-04-07 19:02:44,477 # +-------------------------------------+
2021-04-07 19:02:44,592 # TVOC [ppb]: 3
2021-04-07 19:02:44,594 # eCO2 [ppm]: 400
2021-04-07 19:02:44,597 # +-------------------------------------+
2021-04-07 19:02:44,713 # TVOC [ppb]: 8
2021-04-07 19:02:44,714 # eCO2 [ppm]: 402
2021-04-07 19:02:44,718 # +-------------------------------------+
2021-04-07 19:02:44,833 # TVOC [ppb]: 6
2021-04-07 19:02:44,834 # eCO2 [ppm]: 400
2021-04-07 19:02:44,838 # +-------------------------------------+
2021-04-07 19:02:44,953 # TVOC [ppb]: 2
2021-04-07 19:02:44,954 # eCO2 [ppm]: 400
2021-04-07 19:02:44,958 # +-------------------------------------+
2021-04-07 19:02:45,073 # TVOC [ppb]: 2
2021-04-07 19:02:45,075 # eCO2 [ppm]: 404
2021-04-07 19:02:45,078 # +-------------------------------------+
2021-04-07 19:02:45,193 # TVOC [ppb]: 4
2021-04-07 19:02:45,195 # eCO2 [ppm]: 400
2021-04-07 19:02:45,198 # +-------------------------------------+
2021-04-07 19:02:45,313 # TVOC [ppb]: 5
2021-04-07 19:02:45,315 # eCO2 [ppm]: 411
2021-04-07 19:02:45,318 # +-------------------------------------+
2021-04-07 19:02:45,433 # TVOC [ppb]: 8
2021-04-07 19:02:45,435 # eCO2 [ppm]: 407
2021-04-07 19:02:45,438 # +-------------------------------------+
2021-04-07 19:02:45,553 # TVOC [ppb]: 2
2021-04-07 19:02:45,555 # eCO2 [ppm]: 403
2021-04-07 19:02:45,558 # +-------------------------------------+
2021-04-07 19:02:45,674 # TVOC [ppb]: 5
2021-04-07 19:02:45,675 # eCO2 [ppm]: 406
2021-04-07 19:02:45,679 # +-------------------------------------+
```

- test with saul

```
2021-04-07 19:06:25,179 # ##########################
2021-04-07 19:06:26,163 # 
2021-04-07 19:06:26,166 # Dev: LED(orange)	Type: ACT_SWITCH
2021-04-07 19:06:26,168 # Data:	              0 
2021-04-07 19:06:26,168 # 
2021-04-07 19:06:26,171 # Dev: Button(SW0)	Type: SENSE_BTN
2021-04-07 19:06:26,173 # Data:	              0 
2021-04-07 19:06:26,173 # 
2021-04-07 19:06:26,176 # Dev: sgp30	Type: SENSE_CO2
2021-04-07 19:06:26,178 # Unable to display data object
2021-04-07 19:06:26,179 # 
2021-04-07 19:06:26,181 # Dev: sgp30	Type: SENSE_TVOC
2021-04-07 19:06:26,184 # Unable to display data object
2021-04-07 19:06:26,184 # 
2021-04-07 19:06:26,186 # ##########################
2021-04-07 19:06:27,176 # 
2021-04-07 19:06:27,179 # Dev: LED(orange)	Type: ACT_SWITCH
2021-04-07 19:06:27,181 # Data:	              0 
2021-04-07 19:06:27,181 # 
2021-04-07 19:06:27,184 # Dev: Button(SW0)	Type: SENSE_BTN
2021-04-07 19:06:27,186 # Data:	              0 
2021-04-07 19:06:27,186 # 
2021-04-07 19:06:27,189 # Dev: sgp30	Type: SENSE_CO2
2021-04-07 19:06:27,192 # Data:	            400 ppm
2021-04-07 19:06:27,192 # 
2021-04-07 19:06:27,194 # Dev: sgp30	Type: SENSE_TVOC
2021-04-07 19:06:27,196 # Data:	              0 ppb
2021-04-07 19:06:27,197 # 
2021-04-07 19:06:27,199 # ##########################
2021-04-07 19:06:28,177 # 
2021-04-07 19:06:28,179 # Dev: LED(orange)	Type: ACT_SWITCH
2021-04-07 19:06:28,182 # Data:	              0 
2021-04-07 19:06:28,182 # 
2021-04-07 19:06:28,198 # Dev: Button(SW0)	Type: SENSE_BTN
2021-04-07 19:06:28,200 # Data:	              0 
2021-04-07 19:06:28,200 # 
2021-04-07 19:06:28,202 # Dev: sgp30	Type: SENSE_CO2
2021-04-07 19:06:28,205 # Data:	            400 ppm
2021-04-07 19:06:28,205 # 
2021-04-07 19:06:28,208 # Dev: sgp30	Type: SENSE_TVOC
2021-04-07 19:06:28,210 # Data:	              0 ppb
2021-04-07 19:06:28,210 # 
2021-04-07 19:06:28,212 # ##########################

```

2021-04-08 08:03 UTC, kaspar030 commented
please squash (and rebase)!

2021-04-08 08:03 UTC, kaspar030 approved these changes
ACK.

2021-04-08 08:13 UTC, fjmolinas commented on drivers/saul/init_devs/init.c
> +        auto_init_sgp30();
Bodged the rebase

2021-04-08 08:15 UTC, fjmolinas commented on drivers/saul/init_devs/init.c
> +        auto_init_sgp30();
addressed

2021-04-08 08:15 UTC, fjmolinas commented
Rebased and squashed.

2021-04-08 15:55 UTC, fjmolinas commented
All green @kaspar030!

2021-04-09 12:00 UTC, merged