sys/event: add periodic timeout event
RIOT-OS/RIOT pull request #16507
Opened 2021-05-28 09:33 UTC by fjmolinas

### Contribution description

This PR adds a periodic timeout event using `ztimer`. Useful to scheduler a task that should be periodically executed, e.g.: reading some sensor.

### Testing procedure

`make -C tests/event_timeout_ztimer`

### Issues/PRs references

depend on #16505

2021-06-01 10:19 UTC, kaspar030 commented
please rebase!

2021-06-01 12:02 UTC, kaspar030 requested changes

2021-06-01 12:32 UTC, fjmolinas commented
<details><summary><b>BOARD=dwm1001 make -C tests/riotboot_flashwrite/ flash test-with-config
</b></summary>

```
_flashwrite_handler(): received data: offset=8704 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=8768 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=8832 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=8896 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=8960 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9024 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9088 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9152 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9216 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9280 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9344 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9408 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9472 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9536 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9600 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9664 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9728 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9792 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9856 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9920 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=9984 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10048 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10112 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10176 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10240 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10304 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10368 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10432 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10496 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10560 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10624 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10688 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10752 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10816 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10880 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=10944 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11008 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11072 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11136 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11200 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11264 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11328 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11392 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11456 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11520 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11584 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11648 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11712 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11776 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11840 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11904 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=11968 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12032 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12096 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12160 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12224 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12288 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12352 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12416 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12480 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12544 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12608 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12672 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12736 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12800 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12864 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12928 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=12992 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13056 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13120 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13184 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13248 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13312 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13376 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13440 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13504 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13568 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13632 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13696 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13760 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13824 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13888 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=13952 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14016 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14080 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14144 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14208 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14272 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14336 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14400 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14464 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14528 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14592 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14656 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14720 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14784 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14848 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14912 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=14976 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=15040 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=15104 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=15168 len=64 blockwise=1 more=1
_flashwrite_handler(): received data: offset=15232 len [...]

2021-06-01 13:39 UTC, fjmolinas commented on sys/event/periodic_timeout.c
> +
done

2021-06-01 13:39 UTC, fjmolinas commented on sys/include/event/timeout.h
> +#if IS_USED(MODULE_EVENT_PERIODIC_TIMEOUT)
done

2021-06-01 13:39 UTC, fjmolinas commented
@kaspar030 may I squash?

2021-06-01 13:51 UTC, kaspar030 commented on sys/include/event/timeout.h
> +
(nit) double newline

2021-06-02 07:55 UTC, kaspar030 commented
I think "event_periodic" would suffice as a name (drop the "timeout"). What do you think?

2021-06-03 16:03 UTC, fjmolinas commented
> I think "event_periodic" would suffice as a name (drop the "timeout"). What do you think?

dropped.

2021-06-04 07:40 UTC, fjmolinas commented
Unrelated test failures

2021-06-07 07:43 UTC, fjmolinas commented
Unrelated test failure:

![image](https://user-images.githubusercontent.com/23060007/120978427-bdd63d00-c774-11eb-9d2e-f8092c8ec524.png)

https://ci.riot-os.org/RIOT-OS/RIOT/16507/b0396eec5a59b20cd978ff9973475be3b6755ba1/output/run_test/tests/congure_test/samr21-xpro:gnu.txt

Will re-run without tests :)

2021-06-08 11:07 UTC, merged