pkg/wakaama: remove gnrc dependency
RIOT-OS/RIOT pull request #16563
Opened 2021-06-16 16:13 UTC by jia200x

### Contribution description
This PR removes the only dependency to GNRC that was present in the Wakaama example, since https://github.com/RIOT-OS/RIOT/pull/12738 was already merged some time ago.

With this change it should be possible to run Wakaama with other network stacks (e.g LWIP ~and soon OpenThread~)

### Testing procedure
Run `examples/wakaama`

### Issues/PRs references
https://github.com/RIOT-OS/RIOT/pull/12738

2021-06-18 11:32 UTC, MrKevinWeiss commented
Tested this and master, both seem to perform the same (equally flake :laughing: )

2021-06-18 11:34 UTC, MrKevinWeiss approved these changes
I guess it is OK, if anyone else has anything to say now is the time.

2021-06-18 12:31 UTC, leandrolanzieri requested changes
While trying to make it work with a different stack with @jia200x we found a reference to a gnrc-implementation specific member of `sock_udp_t`, so it would be nice to change that as well...

2021-06-22 12:51 UTC, MrKevinWeiss commented
ping @jia200x

2021-06-22 14:13 UTC, jia200x commented
fixed!

2021-06-22 14:32 UTC, leandrolanzieri approved these changes
Nice to have this finally stack independent! I tested on GNRC and the example works as expected. I understand @jia200x made it work with LWIP after implementing some `netif` functions that are missing for that stack.

ACK!

2021-06-22 16:08 UTC, jia200x commented
thanks for the review!

2021-06-22 16:08 UTC, merged