examples/hello-world: blink LED, if any
RIOT-OS/RIOT pull request #16582
Opened 2021-06-23 19:43 UTC by maribu

### Contribution description

After printing the hello world message, an infinite loop is added that blinks `LED0` if provided. This is particularly useful for showcasing new boards that are in the process of being ported to RIOT, so that no stdio is available yet. Consequently, the delay is done without relying on hardware timers being available / supported.

### Testing procedure

```
make BOARD=SOME_BOARD_WITH_AT_LEAST_ONE_LED -C examples/hello_world flash term
```

In addition to the unchanged output via stdio, the first led should blink with a period in the order of 2 seconds. The exact timing doesn't matter, it should only be noticeably by users.

### Issues/PRs references

None

2021-06-24 06:28 UTC, kaspar030 requested changes
Let's please not change the hello world. It is supposed to be just that, and has been stable for a decade.

Maybe it is time for a proper "blinky", though!

2021-06-24 07:58 UTC, aabadie commented
> Maybe it is time for a proper "blinky"

I remember me when I opened #7506, back in 2017. Let's hope the discussion won't take the same path this time.

2021-06-24 08:00 UTC, kaspar030 commented
> I remember me when I opened #7506, back in 2017. Let's hope the discussion won't take the same path this time.

yeah ... should've merged it back then. let's this time use it as an excuse to avoid feature creep in hello-world.

@maribu: probs for the pic!

2021-06-24 12:04 UTC, miri64 commented
> <img alt="RPi pico blinky" width="30%" src="https://github.com/maribu/images/raw/master/rpi-pico-blinky.gif">

:laughing: :+1:

2021-07-04 13:56 UTC, benpicco approved these changes

2021-07-04 18:47 UTC, maribu commented
Ups. Better make sure that I not view a cached version of the page before triggering Murdock :-(

2021-07-04 19:18 UTC, kaspar030 commented on examples/blinky/main.c
> + * @brief       Hello World application
Blinky

2021-07-05 22:24 UTC, merged

2021-07-06 07:16 UTC, maribu commented
Thanks!