sys/evtimer: use ztimer_sec instead of ztimer_now64 now_min
RIOT-OS/RIOT pull request #16697
Opened 2021-08-02 14:51 UTC by fjmolinas

### Contribution description

Since all timers are extended, using ZTIMER_SEC for evtimer_now_min
gives enough resolution(+3000years, or ~+2000 years since current
epoch) without the need of carrying a 64bit timestamp for all
'ztimer_now_t' types.

Whenever I pull in GNRC I end up having ztimer_now64 pulled in which transforms all my `ztimer_now_t` into 64bits timestamps, this seems quite wasteful when the only function really needing this resolution is `evtimer_now_min`. If used as system time or as an epoch (since 1900), this gives enough resolution for +3000/+2000 years, which seems enough by a longshot.

Since GNRC is the only module using this maybe @miri64 should take a look? I might be overlooking something important.

### Testing procedure

All `tests/evtimer*` pass, maybe @miri64 can suggest more testing?

```
./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . native --applications="tests/evtimer*"
INFO:native:Saving toolchain
INFO:native.tests/evtimer_mbox:Board supported: True
INFO:native.tests/evtimer_mbox:Board has enough memory: True
INFO:native.tests/evtimer_mbox:Application has test: True
INFO:native.tests/evtimer_mbox:Run compilation
INFO:native.tests/evtimer_mbox:Run test
INFO:native.tests/evtimer_mbox:Run test.flash
INFO:native.tests/evtimer_mbox:Success
INFO:native.tests/evtimer_msg:Board supported: True
INFO:native.tests/evtimer_msg:Board has enough memory: True
INFO:native.tests/evtimer_msg:Application has test: True
INFO:native.tests/evtimer_msg:Run compilation
INFO:native.tests/evtimer_msg:Run test
INFO:native.tests/evtimer_msg:Run test.flash
INFO:native.tests/evtimer_msg:Success
INFO:native.tests/evtimer_underflow:Board supported: True
INFO:native.tests/evtimer_underflow:Board has enough memory: True
INFO:native.tests/evtimer_underflow:Application has test: True
INFO:native.tests/evtimer_underflow:Run compilation
INFO:native.tests/evtimer_underflow:Run test
INFO:native.tests/evtimer_underflow:Run test.flash
INFO:native.tests/evtimer_underflow:Success
INFO:native:Tests successful
```

2021-08-02 17:39 UTC, miri64 requested changes
NACK, as this is a public API function, this can be a potential foot gun. Even though currently it is only used to determine the offset for the ABR lifetimes (and thus `evtimer_now_min()` is always used against another `evtimer_now_min()`), one might get the idea that using this savely against a value generated with `evtimer_now_msec()` might be a good idea (which, since the values could come from different clocks isn't at all).

2021-08-02 17:39 UTC, miri64 commented
(so this is not about GNRC, but API consistency)

2021-08-02 17:40 UTC, miri64 commented
And I believe @kfessel and @maribu will back me on this.

2021-08-02 18:55 UTC, maribu commented
I agree with @miri64.

More generally, I wonder if we should reconsider whether allowing `ztimer_now()` on clocks with a different epochs is a good idea. IMO thisis a non-obvious footgun that is just waiting to blast off.

The alternatives that come to my mind are:

1. Allow only one "main" clock to provide timestamps
    * + Absolutely foot-gun free
    * + Trivial to implement
    * - Which should be the "main" clock? What when two modules have a conflicting requirements regarding the "main" clock?
    * - manually converting between time scales is really meh, especially since ztimer implements the conversion logic fine
2. Allow all clocks derived from the "main" hardware clock to provide timestamps
    * + a bit more convenient than 1.
    * - replaces one footgun by another (IMO it is quite surprising that making use of an RTT could result in some clocks loosing their timestamping features)
3. Synchronise the ztimer backends
    * - a horrible idea IMO, since clocks will drift. Mixing timestamps from different sources will result in different durations being reported for the same real duration depending on which clock was used for the start and which for the stop timestamp.
    * - overhead / complexity
4. Always use the same hardware clock for timestamps. (E.g even if ZTIMER_USEC would use periph_timer for timers, still use periph_rtt and frequency conversion for timestamps.)
    * + no big footguns and relatively easy
    * - different resolutions for timers and timestamps
    * - clock drift between timestamps and timers. (If timer duration are dynamically computed from durations measured using the delta of two timestamps, that could be an issue).
5. Drop access to timestamps altogether. Instead, allow only to measure durations by providing two functions (for start and stop) which operate on an opaque `struct`. With develhelp the struct would contain a pointer to the clock it was started on and the stop function `assert()`s the same being used there. The stop function would be allowed to be called multiple times for the same starting value and a convenience "epoch" starting value for each clock could be provided for when timestamps are needed.
    * + No loss of functionality
    * + No overhead when not using DEVELHELP
    * + Fixes the footgun
    * + The convenience epoch values could be compile time constants to allow them to be garbage collected at link time. Also, they could be randomly chosen at built time to ensure mixing "timestamps" from different clocks fails soon and noisy.
    * - More verbose code
    * - Some overhead (one pointer and an `asserr()`) when using DEVELHELP

2021-08-02 19:41 UTC, miri64 commented
You might want to open an issue (and maybe even an additional forum thread?) to discuss and put emphasis on this outside of this PR ;-).

2021-08-02 19:51 UTC, miri64 commented
In case this won't happen, here are some of my concerns:

1. Can lead to potential granularity problems. Alternatively, too high granularity if we actually only need e.g. a scale of minutes for the time stamps (potential for too rapid overflows).
2. Same problem, if I understand it correctly.
3. I agree with your statement that this is a horrible idea ;-).
4. As you pointed out: same problem as with 1 and 2
5. Not doable if you want to derive e.g. networking functionality. Sometimes (e.g. in 6LoWPAN and IPv6 reassembly buffer) time of arrival needs to be stored. Also can be quite cumbersome if applications want to e.g. set certain timings for sensors / actuators.  Some notion of "now" also is required for e.g. stuff like [SenML](https://datatracker.ietf.org/doc/html/rfc8428#section-4.5.3).

2021-08-03 06:32 UTC, fjmolinas commented
> NACK, as this is a public API function, this can be a potential foot gun. Even though currently it is only used to determine the offset for the ABR lifetimes (and thus `evtimer_now_min()` is always used against another `evtimer_now_min()`), one might get the idea that using this safely against a value generated with `evtimer_now_msec()` might be a good idea (which, since the values could come from different clocks isn't at all).

Ah true, I completely forgot that the base timer is most of the time not the same..., so I agree with the footgun point.

2021-08-03 06:32 UTC, closed without merging