boards/nrf52: replace gnrc_netdev_default with netdev_default
RIOT-OS/RIOT pull request #16788
Opened 2021-08-31 08:49 UTC by benpicco

### Contribution description

There should be nothing GNRC specific about those radio drivers.

### Testing procedure

`gnrc_netdev_default` selects `netdev_default` so binaries will stay the same.

### Issues/PRs references

2021-08-31 13:50 UTC, miri64 submitted a review, later dismissed
ACK

2021-08-31 13:56 UTC, miri64 requested changes

2021-08-31 13:56 UTC, miri64 commented on boards/common/nrf52/Makefile.nimble.dep
>    endif
```suggestion
  ifneq (,$(filter gnrc,$(USEMODULE)))
    ifeq (,$(filter nrfmin nrf802154,$(USEMODULE)))
      USEMODULE += nimble_netif
    endif
  endif
```

2021-09-02 11:59 UTC, miri64 requested changes
Only now realized that you were a bit too zealous in following my instructions ;-).

2021-09-02 11:59 UTC, miri64 commented on boards/common/nrf52/Makefile.nrfmin.dep
> +  ifneq (,$(filter gnrc,$(USEMODULE)))
`nrfmin` should work without `gnrc` so checking for `gnrc` here should not be necessary.

2021-09-02 12:28 UTC, miri64 commented
> Please squash!

Still valid :-)

2021-09-02 12:34 UTC, miri64 commented
> There should be nothing GNRC specific about those radio drivers.

From your commit message. That may need a smallish update ;-).

2021-09-03 11:36 UTC, benpicco commented
I changed the commit text

2021-09-03 12:36 UTC, miri64 approved these changes
ACK

2021-09-03 12:37 UTC, merged