Ztimer convert some benches
RIOT-OS/RIOT pull request #17098
Opened 2021-11-02 08:26 UTC by kaspar030

### Contribution description

This PR converts some `tests/bench_*` to ztimer.

### Testing procedure

### Issues/PRs references

2021-11-02 10:08 UTC, bergzand commented
This PR breaks the printing of the "ticks" result in the output.


<details><summary>With Ztimer on nrf52840dk `tests/bench_mutex_pingpong/`</summary>

```
2021-11-02 10:59:37,741 # Help: Press s to start test, r to print it is ready
s
2021-11-02 10:59:39,327 # START
2021-11-02 10:59:39,332 # main(): This is RIOT! (Version: 2022.01-devel-326-gee721-HEAD)
2021-11-02 10:59:39,334 # main starting
2021-11-02 10:59:40,325 # { "result" : 115108 }
```

</details>

<details><summary>current master on nrf52840dk `tests/bench_mutex_pingpong/`</summary>

```
2021-11-02 11:00:16,351 # Help: Press s to start test, r to print it is ready
s
2021-11-02 11:00:17,230 # START
2021-11-02 11:00:17,236 # main(): This is RIOT! (Version: 2022.01-devel-318-gf64b16-HEAD)
2021-11-02 11:00:17,237 # main starting
2021-11-02 11:00:18,229 # { "result" : 115108, "ticks" : 555 }
```

</details>

2021-11-02 12:00 UTC, kaspar030 commented
> This PR breaks the printing of the "ticks" result in the output.

thanks for looking at the actual output. the benchmarks were missing an include for "periph_conf.h" and "timex.h", which previously were included through xtimer.h.

2021-11-03 09:25 UTC, bergzand commented
Both on the nrf52840dk

<details> <summary> `tests/bench_sys_atomic_utils` on master </summary>

```
2021-11-03 10:20:57,349 # +------+----------+------+------------------+------------------+------------------+
2021-11-03 10:20:57,356 # | mode |       op | bits |         volatile |      atomic util |       c11 atomic |
2021-11-03 10:20:57,363 # +------+----------+------+------------------+------------------+------------------+
2021-11-03 10:20:57,400 # | atom |    store |    8 |          6252 µs |         12501 µs |         10939 µs |
2021-11-03 10:20:57,437 # | atom |    store |   16 |          6252 µs |         12501 µs |         10939 µs |
2021-11-03 10:20:57,470 # | atom |    store |   32 |          6252 µs |          9377 µs |          9377 µs |
2021-11-03 10:20:57,549 # | atom |    store |   64 |          9376 µs |         17189 µs |         45314 µs |
2021-11-03 10:20:57,586 # | atom |     load |    8 |          7815 µs |         10939 µs |         10939 µs |
2021-11-03 10:20:57,623 # | atom |     load |   16 |          7814 µs |         10939 µs |         10939 µs |
2021-11-03 10:20:57,660 # | atom |     load |   32 |          7815 µs |         10939 µs |         10939 µs |
2021-11-03 10:20:57,723 # | atom |     load |   64 |          9376 µs |         15627 µs |         31252 µs |
2021-11-03 10:20:57,785 # | atom |      add |    8 |         12501 µs |         20314 µs |         21877 µs |
2021-11-03 10:20:57,850 # | atom |      add |   16 |         14064 µs |         18751 µs |         25002 µs |
2021-11-03 10:20:57,910 # | atom |      add |   32 |         10939 µs |         17189 µs |         25002 µs |
2021-11-03 10:20:58,017 # | atom |      add |   64 |         17189 µs |         25002 µs |         57814 µs |
2021-11-03 10:20:58,075 # | atom |      sub |    8 |         12502 µs |         18751 µs |         20314 µs |
2021-11-03 10:20:58,134 # | atom |      sub |   16 |         12502 µs |         18752 µs |         20314 µs |
2021-11-03 10:20:58,200 # | atom |      sub |   32 |         10939 µs |         23439 µs |         25001 µs |
2021-11-03 10:20:58,318 # | atom |      sub |   64 |         18752 µs |         23439 µs |         68752 µs |
2021-11-03 10:20:58,383 # | atom |       or |    8 |         15626 µs |         21877 µs |         20315 µs |
2021-11-03 10:20:58,448 # | atom |       or |   16 |         18752 µs |         18752 µs |         20314 µs |
2021-11-03 10:20:58,505 # | atom |       or |   32 |         10940 µs |         18752 µs |         20314 µs |
2021-11-03 10:20:58,624 # | atom |       or |   64 |         17189 µs |         35939 µs |         59377 µs |
2021-11-03 10:20:58,683 # | atom |      xor |    8 |         12501 µs |         18752 µs |         20315 µs |
2021-11-03 10:20:58,752 # | atom |      xor |   16 |         17190 µs |         25001 µs |         20314 µs |
2021-11-03 10:20:58,817 # | atom |      xor |   32 |         10939 µs |         21876 µs |         25002 µs |
2021-11-03 10:20:58,945 # | atom |      xor |   64 |         25002 µs |         31251 µs |         65627 µs |
2021-11-03 10:20:59,004 # | atom |      and |    8 |         12502 µs |         18751 µs |         20314 µs |
2021-11-03 10:20:59,061 # | atom |      and |   16 |         10939 µs |         18752 µs |         20315 µs |
2021-11-03 10:20:59,126 # | atom |      and |   32 |         10939 µs |         21877 µs |         25002 µs |
2021-11-03 10:20:59,251 # | atom |      and |   64 |         25001 µs |         32814 µs |         60939 µs |
2021-11-03 10:20:59,308 # | atom |      set |    8 |         12502 µs |         17190 µs |         20315 µs |
2021-11-03 10:20:59,376 # | atom |      set |   16 |         14064 µs |         20314 µs |         26564 µs |
2021-11-03 10:20:59,432 # | atom |      set |   32 |         10939 µs |         17189 µs |         20314 µs |
2021-11-03 10:20:59,571 # | atom |      set |   64 |         26565 µs |         32814 µs |         73439 µs |
2021-11-03 10:20:59,628 # | atom |    clear |    8 |         10939 µs |         18752 µs |         20314 µs |
2021-11-03 10:20:59,691 # | atom |    clear |   16 |         14064 µs |         21877 µs |         20314 µs |
2021-11-03 10:20:59,759 # | atom |    clear |   32 |         15627 µs |         18752 µs |         26564 µs |
2021-11-03 10:20:59,888 # | atom |    clear |   64 |         25001 µs |         31252 µs |         65627 µs |
2021-11-03 10:20:59,953 # | semi |      add |    8 |         14065 µs |         18752 µs |         25001 µs |
2021-11-03 10:21:00,024 # | semi |      add |   16 |         14064 µs |         25001 µs |         25002 µs |
2021-11-03 10:21:00,089 # | semi |      add |   32 |         10940 µs |         21877 µs |         25002 µs |
2021-11-03 10:21:00,211 # | semi |      add |   64 |         25001 µs |         32815 µs |         57815 µs |
2021-11-03 10:21:00,283 # | semi |      sub |    8 |         18751 µs |         21877 µs |         25002 µs |
2021-11-03 10:21:00,354 # | semi |      sub |   16 |         14064 µs |         25002 µs |         25002 µs |
2021-11-03 10:21:00,419 # | semi |      sub |   32 |         10939 µs |         21877 µs |         25001 µs |
2021-11-03 10:21:00,536 # | semi |      sub |   64 |         18752 µs |         23439 µs |         68752 µs |
2021-11-03 10:21:00,601 # | semi |       or |    8 |         12502 µs |         25001 µs |         20314 µs |
2021-11-03 10:21:00,666 # | semi |       or |   16 |         18751 µs |         18752 µs |         20315 µs |
2021-11-03 10:21:00,734 # | semi |       or |   32 |         15627 µs |         18752 µs |         26564 µs |
2021-11-03 10:21:00,858 # | semi |       or |   64 |         25002 µs |         32814 µs |         59376 µs |
2021-11-03 10:21:00,918 # | semi |      xor |    8 |         15627 µs |         17190 µs |         20314 µs |
2021-11-03 10:21:00,983 # | semi |      xor |   16 |         12502 µs |         20314 µs |         25001 µs |
2021-11-03 10:21:01,040 # | semi |      xor |   32 |         10939 µs |         18752 µs |         20314 µs |
2021-11-03 10:21:01,168 # | semi |      xor |   64 |         25001 µs |         35939 µs |         60939 µs |
2021-11-03 10:21:01,233 # | semi |      and |    8 |         12502 µs |         20314 µs |         25002 µs |
2021-11-03 10:21:01,298 # | semi |      and |   16 |         12502 µs |         25002 µs |         20314 µs |
2021-11-03 10:21:01,361 # | semi |      and |   32 |         10940 µs |         18752 µs |         26565 µs |
2021-11-03 10:21:01,492 # | semi |      and |   64 |         28127 µs |         35939 µs |         60939 µs |
2021-11-03 10:21:01,500 # +------+----------+------+------------------+------------------+------------------+
```

</details>
<details> <summary> `tests/bench_sys_atomic_utils` this PR </summary>

```
2021-11-03 10:20:05,454 # +------+----------+------+------------------+------------------+------------------+
2021-11-03 10:20:05,461 # | mode |       op | bits |         volatile |      atomic util |       c11 atomic |
2021-11-03 10:20:05,469 # +------+----------+------+------------------+------------------+------------------+
2021-11-03 10:20:05,515 # | atom |    store |    8 |          6251 µs |         23439 µs |          9376 µs |
2021-11-03 10:20:05,561 # | atom |    store |   16 |          6251 µs |         23438 µs |          9376 µs |
2021-11-03 10:20:05,604 # | atom |    store |   32 |          6252 µs |         18751 µs |         10938 µs |
2021-11-03 10:20:05,685 # | atom |    store |   64 |          9376 µs |         17189 µs |         46876 µs |
2021-11-03 10:20:05,736 # | atom |     load |    8 |          7814 µs |         25001 µs |         10939 µs |
2021-11-03 10:20:05,785 # | atom |     load |   16 |         10939 µs |         20313 µs |         10939 µs |
2021-11-03 10:20:05,842 # | atom |     load |   32 |         10939 µs |         26564 µs |         12501 µs |
2021-11-03 10:20:05,906 # | atom |     load |   64 |          9376 µs |         15627 µs |         31251 µs  [...]

2021-11-03 09:44 UTC, bergzand requested changes

2021-11-03 09:44 UTC, bergzand commented on tests/bench_thread_yield_pingpong/main.c
>  #include "macros/units.h"
This test is still missing the includes for `CLOCK_CORECLOCK`

```suggestion
#include "periph_conf.h"
#include "timex.h"
#include "macros/units.h"
```

2021-12-07 08:21 UTC, fjmolinas commented
@kaspar030 seems like its only missing some dependencies and board blacklisting

2022-01-17 10:59 UTC, fjmolinas commented
Please squash!

2022-03-09 11:28 UTC, OlegHahm commented
@kaspar030, ping!

2024-03-01 09:39 UTC, kaspar030 commented
I'm not going to work on this anymore.

2024-03-01 09:39 UTC, closed without merging