build system: add convenience PICOLIBC variable
RIOT-OS/RIOT pull request #17129
Opened 2021-11-03 15:04 UTC by benpicco

### Contribution description

Before picolibc was a feature, it could be selected by adding

    PICOLIBC=1

to the build command line (similar to `LTO=1`).

Bring this feature back since it's easier to type than adding

    FEATURES_REQUIRED += picolibc

to the application Makefile

### Testing procedure

Build any application with `PICOLIBC=1` (and observe the size decrease of the binary) 

### Issues/PRs references

brings back feature dropped in #15011

2021-11-03 15:42 UTC, fjmolinas requested changes
I don't like adding another layer for an interface that already exists, it makes the build-system messier than it already is.

2021-11-03 16:57 UTC, kfessel commented
> I don't like adding another layer for an interface that already exists, it makes the build-system messier than it already is.

Does it realy exist?
this is for command line convenience - read never use within a Makefile

it is 
` 
PICOLIBC=1 make
`
vs 
`
FEATURES_REQUIRED=picolibc make
`

2021-11-03 17:19 UTC, benpicco commented
The problem with `FEATURES_REQUIRED=picolibc make` (other than that it's more awkward to type) is that the order matters.

e.g. `make FEATURES_REQUIRED=picolibc` will overwrite the `FEATURES_REQUIRED` list of the application Makefile (if it exists)

2021-11-04 07:34 UTC, fjmolinas commented
> The problem with `FEATURES_REQUIRED=picolibc make` (other than that it's more awkward to type) is that the order matters.

> e.g. `make FEATURES_REQUIRED=picolibc` will overwrite the `FEATURES_REQUIRED` list of the application Makefile (if it exists)

I understand but that is just how `make` works, `make` arguments and environment variables are not the same and not handled the same way. You want this commodity for `picolibc`, but then why not have it for `newlib` or for `MODULE`, this is why I mean it can get messy. The fact that order matters might not be user-friendly, but having things like `BOARD` have custom handling worsens it because it leads to different expectations IMO.

2022-08-13 19:35 UTC, closed without merging