boards/lora-e5-dev: extended documentation
RIOT-OS/RIOT pull request #17244
Opened 2021-11-19 20:50 UTC by fjmolinas

### Contribution description

Had to extend the documentation for a course, better do it in the tree...

### Testing procedure

Circle ci.

2021-11-20 17:30 UTC, aabadie requested changes
Found some typos and some sentences can be reworded a bit.

2021-11-20 17:30 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * The LoRa-E5 Dev Board is an evaluation BOARD for the Seeed Studio LoRa-E5 STM32WLE5JC
```suggestion
 * The LoRa-E5 Dev Board is an evaluation board for the Seeed Studio LoRa-E5 STM32WLE5JC
```

Do you have some sort of auto correction enabled or do you really write _board_ capitalized ?

2021-11-20 17:30 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * module. The cpu includes a radio supporting a multiple LPWAN protocols in the
```suggestion
 * module. The cpu includes a radio supporting multiple LPWAN protocols in the
```

2021-11-20 17:30 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * Arduino style pin headers, there are nor arduino compatible.
```suggestion
 * Convenient interfaces as Grove and RS-485 are mapped out, and the many pins
 * map most of the modules GPIOs. But watch out! Although it features
 * Arduino style pin headers, there are not arduino compatible.
```

2021-11-20 17:30 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * external power lines which can enables or disabled by software.
```suggestion
 * external power lines which can be enabled or disabled by software.
```

2021-11-20 17:30 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * external power lines which can enables or disabled by software.
```suggestion
 * external power lines which can be enabled or disabled by software.
```

2021-11-20 17:30 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * else then read protection needs to be set back to level 0.
```suggestion
 * The BOARD comes pre-flashed with a DFU bootloader, an AT command Firmware
 * and read protection enabled and set to 1. So before being able to program anything
 * else, read protection needs to be set back to level 0.
```

2021-11-20 17:30 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * Since there is not ST-LINK programmer on the board an external one
```suggestion
 * Since there is no ST-LINK programmer on the board an external one
```

2021-11-20 17:30 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * needs to be connected. Any Nucleo or STM32Dicovery board can be used for this
```suggestion
 * needs to be connected. Any Nucleo or STM32Discovery board can be used for this
```

2021-11-20 17:30 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * for more details). An examples is seen in the following image:
```suggestion
 * for more details). An example is seen in the following image:
```

2021-11-20 17:30 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * is also selected with `USEMODULE += netdev_default`.
```suggestion
 * This board comes embedded with an `sx126x` based LoRa radio. The precise
 * module that needs to be selected is `USEMODULE += sx126x_stm32wl`, this
 * is also selected with `USEMODULE += netdev_default`.
```

2021-11-20 17:30 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * This BOARD includes a @ref drivers_lm75 temperature sensor. It can be
```suggestion
 * This board includes a @ref drivers_lm75 temperature sensor. It can be
```

2021-11-20 18:27 UTC, fjmolinas commented
Thanks @aabadie amended and squashed in.

2021-11-21 09:04 UTC, aabadie commented on boards/lora-e5-dev/doc.txt
> + * The BOARD comes pre-flashed with a DFU bootloader, an AT command Firmware
```suggestion
 * The board comes pre-flashed with a DFU bootloader, an AT command Firmware
```

I forgot this one :)

2021-11-21 14:22 UTC, fjmolinas commented
push forced the first time from the wrong branch, the second push force fixed it. Sorry...

2021-11-21 14:46 UTC, aabadie approved these changes
ACK

2021-11-21 14:47 UTC, aabadie commented
The [generated doc](https://13602-7370241-gh.circle-artifacts.com/0/doc/group__boards__lora-e5-dev.html) is ok.

2021-11-21 14:47 UTC, merged

2021-11-21 14:57 UTC, fjmolinas commented
Thanks @aabadie!