examples/suit_update: drop mention of coaproot directory
RIOT-OS/RIOT pull request #17740
Opened 2022-03-03 15:40 UTC by benpicco

Creating `coaproot` and serving it via aiocoap is a red herring.

If you follow the instructions you will end up with

    suit_coap: downloading "coap://[2001:db8::1]/fw/same54-xpro/suit_update-riot.suit_signed.latest.bin"
    suit_coap: error getting manifest# Please enter the commit message for your changes. Lines starting

because there is nothing that will ever put something into the `coaproot/` directory.

Instead there is already a symbolic `fw` link in the directory of the test application, so just using the test application directory as the root will
do the right thing.

### Contribution description

### Testing procedure

### Issues/PRs references

2022-03-03 19:39 UTC, chrysn commented
There are a few more mentions of coaproot in examples/suit_update/README.native.md -- should they go as well?

makefiles/suit.inc.mk mentions a SUIT_COAP_FSROOT of that value, what about that?

2022-03-04 10:48 UTC, benpicco commented
The instructions for `native` make sense because they also place something in the `coaproot/` directory (and don't attempt a firmware update).

2022-03-08 09:10 UTC, fjmolinas requested changes
It is used in `suit.inc.mk`, if you run the auto-test its there.

2022-03-08 09:20 UTC, benpicco commented on examples/suit_update/README.hardware.md
> -    $ aiocoap-fileserver coaproot
This was actually correct, I just executed it inside of `examples/suit_update` :sweat_smile:

2022-03-09 07:12 UTC, fjmolinas approved these changes
ACK

2022-03-09 08:08 UTC, merged