gcoap_forward_proxy: provide cache validation mechanism
RIOT-OS/RIOT pull request #17801
Opened 2022-03-11 15:27 UTC by miri64

### Contribution description
This provides support for the [cache validation mechanism of CoAP](https://datatracker.ietf.org/doc/html/rfc7252#section-5.6.2) for the `gcoap_forward_proxy` module if `nanocoap_cache` is also provided.

### Testing procedure
TBD procedurally, but could be easily done with an `aiocoap` server with ETag support, a RIOT client and a RIOT forward proxy inbetween the two. The client requests a resource via the proxy (the server delivers the data with an ETag), waits until the Max-Age (default 60 seconds) of the resource passed, then requests the (assumed to be unchanging) resource again. This should trigger the proxy to send a request with the resource's ETag to the server which in turn answers with a 2.03 Valid response. The proxy should then send the original cached response back (and update the cache entries Max-Age).

### Issues/PRs references
Requires #13889 and its dependencies.

2022-05-11 09:33 UTC, miri64 commented
Rebased and retested on `native` with the testing procedures (I patched `aiocoap`'s fileserver to speed up the testing a bit:

```diff
diff --git a/aiocoap/cli/fileserver.py b/aiocoap/cli/fileserver.py
index 1bf2ba4..f6ce129 100644
--- a/aiocoap/cli/fileserver.py
+++ b/aiocoap/cli/fileserver.py
@@ -160,2 +160,3 @@ class FileServer(Resource, aiocoap.interfaces.ObservableResource):
 
+        response.opt.max_age = 10
         response.opt.etag = etag
```
)

![image](https://user-images.githubusercontent.com/675644/167818341-1f775c9d-901d-4e19-8495-ef0cb7e5a9ad.png)

2022-05-11 09:47 UTC, miri64 commented
Addressed doxygen errors and squashed.

2022-05-11 13:43 UTC, cgundogan requested changes
A few nits.

2022-05-11 13:49 UTC, miri64 commented on sys/net/application_layer/gcoap/forward_proxy.c
> +         * we should hit at least once (and it's opt_num is also >= COAP_OPT_ETAG) */
Addressed

2022-05-11 14:17 UTC, cgundogan commented on sys/net/application_layer/gcoap/forward_proxy.c
> +    uint16_t validating;
From https://gcc.gnu.org/onlinedocs/gccint/Type-Layout.html I read:

>Macro: BOOL_TYPE_SIZE
A C expression for the size in bits of the C++ type bool and C99 type _Bool on the target machine. If you don’t define this, and you probably shouldn’t, the default is CHAR_TYPE_SIZE.

2022-05-11 15:01 UTC, miri64 commented on sys/net/application_layer/gcoap/forward_proxy.c
> +    uint16_t validating;
TIL... was able to confirm for a handful of platforms `sizeof(bool): 1`

2022-05-11 15:01 UTC, miri64 commented on sys/net/application_layer/gcoap/forward_proxy.c
> +    uint16_t validating;
Will adopt the code then.

2022-05-11 15:07 UTC, miri64 commented on sys/net/application_layer/gcoap/forward_proxy.c
> +    uint16_t validating;
Done https://github.com/RIOT-OS/RIOT/pull/17801/commits/76de0c1818e92766a963f52000a5ee950c993b1b

2022-05-11 15:38 UTC, miri64 commented
Squashed as requested off-line

2022-05-12 07:35 UTC, cgundogan commented
I tested more extensively today and found a strange error path:
After a second validation (so waiting *again* at least Max-Age seconds), requests seem to return an internal server error. Have a look at the attached wireshark capture and the Time column.

![image](https://user-images.githubusercontent.com/739129/168016575-a530401a-68da-4b04-b72f-c3822ee544b5.png)

2022-05-12 10:12 UTC, miri64 commented
Mh... that indicates, that the proxy is not able to allocate another cep. Will have a look.

2022-05-12 10:18 UTC, miri64 commented
[fb9a11d](https://github.com/RIOT-OS/RIOT/pull/17801/commits/fb9a11dce89b64a553d587b3f2f6e75fd1eb0262) fixes that. On validation, the client ep was previously not freed correctly :sweat_smile:. Good catch!

2022-05-12 11:12 UTC, cgundogan commented
Alright, I can't reproduce this error anymore with your fix.  Looks good!  Please squash.

2022-05-12 11:24 UTC, cgundogan approved these changes
ACK

2022-05-12 12:50 UTC, merged