cpu/samd51: allow to support ADC0 and ADC1 in the same configuration
RIOT-OS/RIOT pull request #17819
Opened 2022-03-17 10:59 UTC by aabadie

### Contribution description

The current ADC support on SAMD51 only allows to configure lines that use either ADC0 or ADC1. It's not possible different lines that use different ADC device. So for example on the pybadge it's not possible to configure board light sensor (uses ADC1) and Bat voltage measure pin (uses ADC0).

This PR extend the ADC line configuration with an extra pointer to the ADC device. This is only possible on cpu with ADC0 and ADC1 available.

The adafruit-pybadge, adafruit-itsybitsy and same52-xpro board configurations are adapted accordingly and on the pybadge, the configuration is extended with more lines that use ADC0 device, including the VMEAS pin.

### Testing procedure

- Green Murdock
- ADC configuration is still working on modified boards. I haven't tried the new ADC configured on the Pybadge, because I'm missing hardware for that but the light sensor is still working as before
- Code size should remain unchange on other CPU. I checked with `tests/periph_adc` on sam21-xpro and this is the case (I can report the output if requested)

### Issues/PRs references

Noticed that limitation when working on #17807

2022-03-17 19:55 UTC, dylad commented on boards/adafruit-pybadge/include/periph_conf.h
> +    {GPIO_PIN(PA, 5), ADC_INPUTCTRL_MUXPOS(ADC_INPUTCTRL_MUXPOS_AIN5), ADC0},   /* A1 */
Any reason not to add A0 ?

2022-03-17 20:03 UTC, dylad requested changes
Spotted a few misconfigurations.

2022-03-17 20:03 UTC, dylad commented on boards/adafruit-pybadge/include/periph_conf.h
> +    {GPIO_PIN(PB, 9), ADC_INPUTCTRL_MUXPOS(ADC_INPUTCTRL_MUXPOS_AIN3), ADC1},   /* A3 */
PB09 -> ADC0, AIN3 / ADC1,AIN1

2022-03-18 08:20 UTC, aabadie commented on boards/adafruit-pybadge/include/periph_conf.h
> +    {GPIO_PIN(PA, 5), ADC_INPUTCTRL_MUXPOS(ADC_INPUTCTRL_MUXPOS_AIN5), ADC0},   /* A1 */
It's used by the speaker

2022-03-18 08:37 UTC, aabadie commented on boards/adafruit-pybadge/include/periph_conf.h
> +    {GPIO_PIN(PB, 8), ADC_INPUTCTRL_MUXPOS(ADC_INPUTCTRL_MUXPOS_AIN2), ADC1},   /* A2 */
Thanks, good spot. I was confused by the Adafruit schematics and haven't checked the datasheet.

2022-03-18 08:53 UTC, aabadie commented
Tested all ADC lines configured and everything is fine now. Thanks!

2022-03-18 09:36 UTC, dylad approved these changes
Looks good to me.

2022-03-18 13:09 UTC, merged