core/assert: print backtrace on failed assertion
RIOT-OS/RIOT pull request #18100
Opened 2022-05-13 10:07 UTC by benpicco

### Contribution description

If the `backtrace` module is enabled, use it to print a backtrace on a failed assertion. 

### Testing procedure

### Issues/PRs references

2022-05-17 08:41 UTC, fjmolinas commented
Can you show some log output?

2022-05-17 09:04 UTC, benpicco commented
Sure! I just added `assert(0)` to `examples/hello-world` and added the `backtrace` module.

Now unfortunately `backtrace` is only implemented on `native`, so this is not as useful as I had initially hoped.
But nothing stops us for adding a backtrace implementation for e.g. ARM too.

2022-05-19 09:13 UTC, chrysn commented
The documentation in `assert.h` describes that `assert()`'s behavior depends on DEBUG_ASSERT_VERBOSE; it could be updated to also indicate the influence of the BACKTRACE module.

Will this do something sane when an assertion fails in an interrupt handler? (Someone explicitly using backtrace would probably check this themselves, but placing an assert is something innocuous).

2022-05-20 12:05 UTC, maribu commented
> I think it should not make a difference, this is only unwinding stack frames, AFAIR there should be no difference if those are on the interrupt stack or the thread stack.

This is not generally true, as some platforms only back up the program counter and leave backing up the registers to software. E.g. on AVR this is the case each ISR can have a unique stack frame format. Even when you force GCC to spill all registers on to the stack in an ISR, GCC will back up registers in different order depending on its current mood.

@nandojve does have a solution to that, though: https://github.com/RIOT-OS/RIOT/pull/16211

2022-10-12 21:17 UTC, maribu commented
What is needed to get this in?

2022-10-13 15:44 UTC, benpicco commented
Just a review.

2022-10-13 19:30 UTC, maribu approved these changes
ACK. Looks good to me. But let's wait for the feature freeze before hitting merge.

There seem to be some test failing - maybe they were waiting for a specific assert message and got of the rails due to changed console output.

2022-10-14 12:33 UTC, miri64 requested changes

2022-10-14 12:33 UTC, miri64 commented on core/lib/assert.c
> +#endif
As there is no line feed in the line above, the alternative code path should add one (but keep the old format in check, if it is not included)

```suggestion
#if IS_USED(MODULE_BACKTRACE)
    printf("failed assertion. Backtrace:\n"
    backtrace_print();
#endif
```

2023-01-18 07:57 UTC, maribu approved these changes

2023-01-18 08:02 UTC, miri64 approved these changes
bors merge

2023-01-18 14:35 UTC, benpicco commented
bors cancel

bors merge

2023-01-18 14:37 UTC, benpicco commented
bors merge

2023-01-18 21:38 UTC, kaspar030 commented
bors cancel
bors merge

2023-01-19 02:56 UTC, merged