tests/pkg_tinyvcdiff: fix stack overflow
RIOT-OS/RIOT pull request #18878
Opened 2022-11-10 21:55 UTC by maribu

### Contribution description

Move some variables from stack to `.bss` / `.data` to avoid stack overflows, which are detected by the MPU stack guard (e.g. on the Nucleo-F767ZI that I used) and results in the test failing.

### Testing procedure

```
$ make BOARD=nucleo-f767zi -C tests/pkg_tinyvcdiff flash test
```

#### On `master`

```
$ make BOARD=nucleo-f767zi -C tests/pkg_tinyvcdiff flash test
[...]
READY
s
START
main(): This is RIOT! (Version: 2023.01-devel-307-g19021)
..*** RIOT kernel panic:
MEM MANAGE HANDLER

*** halted.

Inside isr -12
```

#### This PR

```
$ make BOARD=nucleo-f767zi -C tests/pkg_tinyvcdiff flash test
[...]
READY
s
START
main(): This is RIOT! (Version: 2023.01-devel-308-g038e3-tests/pkg_tinyvcdiff)
..
OK (2 tests)
```

### Issues/PRs references

2022-11-10 22:52 UTC, kfessel requested changes
If you use the same buffer for two tests that are supposed to fill the buffer with the same data (which it is checked for) the second test may fail (write nothing) and still succeed -> you should invalidate (zero) the buffer between the tests

Why do you move the variable into file namespace instead of making them just static?

2022-11-11 07:49 UTC, maribu commented
> Why do you move the variable into file namespace instead of making them just static?

So that I can reuse the buf and do not increase memory consumption. I added a `meset()` to zero out the buf.

2022-11-11 09:36 UTC, kfessel approved these changes

2022-11-11 11:56 UTC, jue89 commented
Thanks for fixing this!

2022-11-11 15:15 UTC, merged

2022-11-12 08:11 UTC, maribu commented
Backport provided in #18896