boards/arduino-mega2560: add TTY_BOARD_FILTER
RIOT-OS/RIOT pull request #19012
Opened 2022-12-05 10:16 UTC by maribu

### Contribution description

This allows automatically selecting TTY actually belonging to an
Arduino Mega2560 if `MOST_RECENT_PORT=1` is set.

### Testing procedure

```
make BOARD=arduino-mega2560 MOST_RECENT_PORT=1 -C examples/default flash term
```

Should automatically select the TTY of the most recently connected Arduino Mega2560, even if a board of a different type is connect more recently.

### Issues/PRs references

- [ ] depends on (and includes) https://github.com/RIOT-OS/RIOT/pull/19011

2022-12-05 10:17 UTC, maribu commented
(This should be super quick in Murdock, as `can_fast_ci_run.py` should detect that only one board was changed. Hence, no harm in already having this in the CI.)

2022-12-07 16:04 UTC, gschorcht commented
The test fails for me. First I thought that I had to install `pyudev`. But also with `pyudev`, I get the following error:
```
avrdude -c stk500v2 -p m2560 -P  -D -U flash:w:examples/default/bin/arduino-mega2560/default.h

avrdude: ser_open(): can't open device "-D": No such file or directory
```
It seems that the port isn't defined.

2022-12-07 16:05 UTC, gschorcht commented
Ah ok, maybe I have to try it on top of PR #19011

2022-12-07 16:09 UTC, gschorcht commented
> Ah ok, maybe I have to try it on top of PR #19011

No, same error.

2022-12-07 16:41 UTC, maribu commented
Hmm, what is the output of `make list-ttys`?

2022-12-07 17:47 UTC, gschorcht commented
> Hmm, what is the output of make list-ttys?

<details>

```
path         | driver | vendor       | model                                | model_db                                             | serial | ctime    | iface_num
-------------|--------|--------------|--------------------------------------|------------------------------------------------------|--------|----------|----------
/dev/ttyUSB1 | ch341  | 1a86         | USB2.0-Serial                        | HL-340 USB-Serial adapter                            | None   | 16:58:16 | 0        
/dev/ttyUSB0 | cp210x | Silicon Labs | CP2102 USB to UART Bridge Controller | CP2102/CP2109 UART Bridge Controller [CP210x family] | 0001   | 16:57:27 | 0        
```

</details>
Obviously my Arduino MEGA 2560 board is a Chineese clone that doesn't use an ATMEGA16U2 for the USB interface but an CH341 USB-Serial adapter :worried: No wonder that the board isn't detected. I had anywhere an original Arduino MEGA 2560  ADK, but I don't know where.

2022-12-09 12:07 UTC, maribu commented
I updated the PR a bit to also allow adding custom commands to detect the TTYs instead of just a `TTY_BOARD_FILTER` and extended the `ttys.py` to return an error code if no TTY was found. This allows chaining the `ttys.py` command in shell e.g. like

```sh
ttys.py --filter-genuine || ttys.py --filter-clones
```

And for the Arduino Mega 2560 I now overwrite the shell command to fall back to detecting cheap USB UART bridges when no genuine Arduino Mega 2560 board was found. I think this is the best compromise, as it still reliably detects a genuine Arduino Mega 2560 (which we can tell apart by the UDEV data from other USB UART bridges), but won't break usage for clone boards.

2022-12-11 15:29 UTC, gschorcht requested changes

2022-12-11 15:29 UTC, gschorcht commented on doc/doxygen/src/flashing.md
> +run `./dist/tools/user-serial/ttys.py` without arguments and study the output.
```suggestion
run `./dist/tools/usb-serial/ttys.py` without arguments and study the output.
```

2022-12-11 15:34 UTC, gschorcht commented
> And for the Arduino Mega 2560 I now overwrite the shell command to fall back to detecting cheap USB UART bridges when no genuine Arduino Mega 2560 board was found. I think this is the best compromise, as it still reliably detects a genuine Arduino Mega 2560 (which we can tell apart by the UDEV data from other USB UART bridges), but won't break usage for clone boards.

But of course this only works if the Arduino Mega 2560 Clone was connected last.

2022-12-11 15:39 UTC, gschorcht requested changes

2022-12-11 15:39 UTC, gschorcht commented on doc/doxygen/src/flashing.md
> +In the case of the Arduino Mega 2560 the paramters
```suggestion
In the case of the Arduino Mega 2560 the parameters
```

2022-12-11 15:39 UTC, gschorcht commented on doc/doxygen/src/flashing.md
> +run `./dist/tools/user-serial/ttys.py` without arguments and study the output.
Feel free to squash the fixes directly.

2022-12-11 17:41 UTC, gschorcht approved these changes

2022-12-11 17:41 UTC, gschorcht commented
bors merge

2022-12-11 18:01 UTC, maribu commented
Squashed.

bors retry

2022-12-11 18:20 UTC, maribu commented
bors retry

2022-12-11 20:03 UTC, merged

2022-12-11 20:54 UTC, maribu commented
Thx :)

2022-12-12 06:24 UTC, gschorcht commented
Oops, I accidentally restarted a full build in the wrong browser window for this PR.