cpu/sam0_common: add option for taking multiple samples
RIOT-OS/RIOT pull request #19165
Opened 2023-01-18 00:43 UTC by benpicco

### Contribution description

### Testing procedure

### Issues/PRs references

2023-02-15 15:28 UTC, dylad commented on cpu/sam0_common/include/periph_cpu_common.h
> +    ADC_RES_14BIT = 0xfe,                        /**< not supported */
I was about to ask you to add them while we're at it.
Perfect timing !
I'll give it a try by the end of the week.

2023-02-19 20:56 UTC, dylad requested changes
Overall changes looks good to me.
But using `tests/periph_adc` with [RES set to ADC_RES_16BIT](https://github.com/RIOT-OS/RIOT/blob/810f8a83eb0798ff88403603577271caca635231/tests/periph_adc/main.c#L26) doesn't work as expected.
Works fine as long as the ADC line is  below VCC_REF / 2 but it returns an error when we're above VCC_REF / 2.

I guess this is because [this variable](https://github.com/RIOT-OS/RIOT/blob/810f8a83eb0798ff88403603577271caca635231/cpu/sam0_common/periph/adc.c#L328) is set as `int16_t`

2023-02-21 17:27 UTC, benpicco commented
Good catch!

2023-02-23 20:49 UTC, dylad commented
Works as expected now !
Please squash.

2023-02-23 21:29 UTC, dylad approved these changes
ACK

2023-02-23 21:29 UTC, dylad commented
bors merge

2023-02-23 21:36 UTC, benpicco commented
bors merge

2023-02-24 02:25 UTC, merged