doc/doxygen: Enable MathJax
RIOT-OS/RIOT pull request #19481
Opened 2023-04-18 15:13 UTC by maribu

### Contribution description

We definitely need LaTeX formulas in our doc! Why? Because we can!

### Testing procedure

Add a LaTeX formula, e.g. `\f( \mathbf{E} \cdot \mathrm{d} \mathbf{S} ={ \frac{1}{\varepsilon_{0}}}\iiint_{\Omega}\rho \, \mathrm{d} V \f)`, somewhere in a Doxygen comment. The generated HTML doc should display a proper formula, when opened in a web browser with JavaScript support enabled.

### Issues/PRs references

None

2023-04-18 15:17 UTC, maribu commented
Note: Mainly commit https://github.com/RIOT-OS/RIOT/pull/19481/commits/78a44e432bd492da32e6e320a49fbf49454b711e which updates the Doxyfile via `doxygen -u` contributes to the large diff. Actually enabling MathJax support is a one-line change.

2023-04-18 19:37 UTC, maribu commented
```
   Command output:
  
  	warning: ignoring unsupported tag 'CREATE_SUBDIRS_LEVEL' at line 93, file -
  	warning: ignoring unsupported tag 'SHOW_HEADERFILE' at line 623, file -
  	warning: ignoring unsupported tag 'WARN_IF_INCOMPLETE_DOC' at line 841, file -
  	warning: ignoring unsupported tag 'WARN_IF_UNDOC_ENUM_VAL' at line 859, file -
  	warning: ignoring unsupported tag 'WARN_LINE_FORMAT' at line 889, file -
  	warning: ignoring unsupported tag 'INPUT_FILE_ENCODING' at line 960, file -
  	warning: ignoring unsupported tag 'FORTRAN_COMMENT_AFTER' at line 1134, file -
  	warning: ignoring unsupported tag 'HTML_COLORSTYLE' at line 1370, file -
  	warning: ignoring unsupported tag 'DOCSET_FEEDURL' at line 1471, file -
  	warning: ignoring unsupported tag 'FULL_SIDEBAR' at line 1682, file -
  	warning: ignoring unsupported tag 'OBFUSCATE_EMAILS' at line 1713, file -
  	warning: ignoring unsupported tag 'MATHJAX_VERSION' at line 1761, file -
  	warning: ignoring unsupported tag 'DOT_COMMON_ATTR' at line 2483, file -
  	warning: ignoring unsupported tag 'DOT_EDGE_ATTR' at line 2492, file -
  	warning: ignoring unsupported tag 'DOT_NODE_ATTR' at line 2500, file -
  	warning: ignoring unsupported tag 'DIR_GRAPH_MAX_DEPTH' at line 2650, file -
```

I guess I shouldn't have updated the Doxyfile then :) I'll drop the commit.

2023-04-19 08:45 UTC, maribu commented
This seems to just be broken with the Doxygen version in the CI :/

2023-04-21 09:00 UTC, kfessel requested changes
decrease readabilty

consider this: strong vote against

U missed April 1st by a lot

2023-04-21 09:00 UTC, kfessel commented on core/lib/include/clist.h
> + * clist_lpush()        | \f(\mathcal{O}\left(1\right)\f)                           | insert as head (leftmost node)
this mixes  something readable in the plain realy unreadable

2023-04-21 09:00 UTC, kfessel commented on core/lib/include/clist.h
> + * clist_lpush()        | \f(\mathcal{O}\left(1\right)\f)                           | insert as head (leftmost node)
this mixes  something readable in the plain realy unreadable

2023-04-21 09:00 UTC, kfessel commented on doc/doxygen/riot.doxyfile
> +USE_MATHJAX            = YES
```suggestion
USE_MATHJAX            = NO
```

alle uses shown above decrease readabilty by a lot ( most people do not use the rended output of the doxgen

2023-04-25 11:53 UTC, closed without merging