Enable compile_and_test_for_board to skip if nothing changed
RIOT-OS/RIOT pull request #19546
Opened 2023-05-04 11:05 UTC by MrKevinWeiss

### Contribution description

The overall goal of this PR is to be able to keep running the `compile_and_test_for_board.py` script without destroying ones boards.  Useful if you are a board owner that wants to keep testing on master (say with nightlies, say in a CI).

For example, I could now just run and rerun the following:
```
./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . <MY_BOARD> -c
```
and monitor the results, even after updating a branch.

This is because the hashes now get stored with the results (thanks to the `RIOT_TEST_RIOT_TEST_HASH_DIR` var) which means cleaning will not wipe them out.  Specifically in (`<results_base>/<board>/hashes/<app_dir>/test-input-hash.sha1`)

I tried to do as much as I could with make and only alter the python script when needed.

### Testing procedure

Clear results folder and run:
```
./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . native --applications tests/shell -c
```
<details>

```
INFO:native:Saving toolchain
INFO:native.tests/shell:Board supported: True
INFO:native.tests/shell:Board has enough memory: True
INFO:native.tests/shell:Application has test: True
INFO:native.tests/shell:Run compilation
**INFO:native.tests/shell:Hashes match: False**
INFO:native.tests/shell:Run test
INFO:native.tests/shell:Run test.flash
INFO:native.tests/shell:Success
INFO:native:Tests successful
```
</details>

it should execute the test...

Then the same command again should skip it.
<details>

```
INFO:native:Saving toolchain
INFO:native.tests/shell:Board supported: True
INFO:native.tests/shell:Board has enough memory: True
INFO:native.tests/shell:Application has test: True
INFO:native.tests/shell:Run compilation
**INFO:native.tests/shell:Hashes match: True**
INFO:native.tests/shell:Success
INFO:native:Tests successful
```
</details>

Try changing something (say the `tests/shell/01-run.py`) and rerun, it should trigger the test again.
<details>

```
INFO:native:Saving toolchain
INFO:native.tests/shell:Board supported: True
INFO:native.tests/shell:Board has enough memory: True
INFO:native.tests/shell:Application has test: True
INFO:native.tests/shell:Run compilation
**INFO:native.tests/shell:Hashes match: False**
INFO:native.tests/shell:Run test
INFO:native.tests/shell:Run test.flash
INFO:native.tests/shell:Success
INFO:native:Tests successful
```
</details>

...finally, running without the changes check should run the test as usual, even if nothing changes:
```
./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . native --applications tests/shell
```
<details>

```
INFO:native:Saving toolchain
INFO:native.tests/shell:Board supported: True
INFO:native.tests/shell:Board has enough memory: True
INFO:native.tests/shell:Application has test: True
INFO:native.tests/shell:Run compilation
INFO:native.tests/shell:Run test
INFO:native.tests/shell:Run test.flash
INFO:native.tests/shell:Success
INFO:native:Tests successful
```
</details>

### Issues/PRs references

Might help the surprises we got with #19469

2023-05-04 11:13 UTC, MrKevinWeiss commented
Maybe @Teufelchen1 or @kaspar030 would be interested in this.

Some open questions are:
- Is the `test-input-hash-changed` target implemented OK, for example, should I make the full dir if missing?
- Will this affect the current .murdock way of doing things, or can we simplify the script now?
- Does the `RIOT_TEST_HASH_DIR` need to be exported to docker as well (currently the test_like_murdock script does not work with docker since the test-input-hash gets exported to a strange place)?
- The the `<results_base>/<board>/hashes/<app_dir>/test-input-hash.sha1` to keep the hashes persistently (since the typical results dir gets cleaned before) or I rather filter the clean function to ignore .sha1 files?
  -  Should there be a different flag to remove the hashes if desired?
  
Follow-up ideas (not for this PR) would be:
- Export some metadata as well beside the test results (ie, git commit)
- Better recording of the current environment
- Recording of the args used to run the script
- A runner to read in a list of boards and possibly full board environments so that multiple boards can be run at the same time

2023-05-09 09:15 UTC, Teufelchen1 requested changes
Looks fine and works. Please add the documentation.

2023-05-10 09:35 UTC, MrKevinWeiss commented
> Looks fine and works. Please add the documentation.

I added a bit more info in a comment, I don't want to clutter the help string.

2023-05-10 10:04 UTC, Teufelchen1 commented
> Some open questions are:
>    [..]
>
>    * Maybe the result of the make command would be better as a status code or something rather than a string, or at least a better formatted string?

I also thought about that but couldn't come up with an ideal solution. Have you tried a status code?

>    [..]
>
>    * The the `<results_base>/<board>/hashes/<app_dir>/test-input-hash.sha1` to keep the hashes persistently (since the typical results dir gets cleaned before) or I rather filter the clean function to ignore .sha1 files?
>       
>    * Should there be a different flag to remove the hashes if desired?
> 

~~I wouldn't add complexity to a clean. It is probably fine to just remove the .sha1 when the build is cleaned. After all, as I understand this PR, it is intended to ease the burden of repeatedly building applications after small changes? That's not a task where I would clean in between - and if I do, I want a fresh restart including removing the cached files.~~
Misunderstood the question. Could you elaborate? Your typo is putting me off.

> 
> Follow-up ideas (not for this PR) would be:
> 
>    * Export some metadata as well beside the test results (ie, git commit)
> 
>    * Better recording of the current environment
> 
>    * Recording of the args used to run the script
> 
>    * A runner to read in a list of boards and possibly full board environments so that multiple boards can be run at the same time

:+1:

2023-05-10 10:22 UTC, MrKevinWeiss commented
> Misunderstood the question. Could you elaborate? Your typo is putting me off.

Currently the hashes are stored in the following format:
```
<results_base>/<board>/hashes/<app_dir>/test-input-hash.sha1
```

The results are stored in a different format:
```
<results_base>/<board>/<app_dir>/*
```

By default, the script will clean the results if they exist by removing the `<results_base>/<board>/<app_dir>/` directory.

My solution for this was to namespace the hashes directory so it does not get removed between runs (which would defeat the point).

The first question would be, is this a good way to preserve the hashes, by namespacing the `hashes` folder, or should I keep the hashes in the hashes next to the results, for example, `<results_base>/<board>/<app_dir>/test-input-hash.sha1`  and carefully remove the remove everything but the hashes during the typical clean.

The second question would be to add a command (arg flag) to clean the hashes since they will persist until either they are manually removed or the results directory changes.

2023-06-29 09:54 UTC, MrKevinWeiss commented
ping

2023-07-11 11:55 UTC, MrKevinWeiss commented
ping

2023-09-04 12:46 UTC, MrKevinWeiss commented
## RIOT OS Test Results

```
No available nodes!

```

2023-09-04 13:09 UTC, MrKevinWeiss commented
## RIOT OS Test Results

```
No available nodes!

```

2023-09-04 14:07 UTC, MrKevinWeiss commented
## RIOT OS Test Results

```
NODE:0:BOARD:nucleo-l552ze-q: INFO:nucleo-l552ze-q:Saving toolchain
NODE:0:BOARD:nucleo-l552ze-q: INFO:nucleo-l552ze-q.tests/sys/shell:Board supported: True
NODE:0:BOARD:nucleo-l552ze-q: INFO:nucleo-l552ze-q.tests/sys/shell:Board has enough memory: True
NODE:0:BOARD:nucleo-l552ze-q: INFO:nucleo-l552ze-q.tests/sys/shell:Application has test: True
NODE:0:BOARD:nucleo-l552ze-q: INFO:nucleo-l552ze-q.tests/sys/shell:Run test
NODE:0:BOARD:nucleo-l552ze-q: INFO:nucleo-l552ze-q.tests/sys/shell:Run test.flash
NODE:0:BOARD:nucleo-l552ze-q: INFO:nucleo-l552ze-q.tests/sys/shell:Success
NODE:0:BOARD:nucleo-l552ze-q: INFO:nucleo-l552ze-q:Tests successful
RESULT:NODE:0:BOARD:nucleo-l552ze-q: 0

```

2023-09-05 07:48 UTC, MrKevinWeiss commented
### Apps tests

tests/sys/shell

### Boards

- `compile_output.txt` PASS

- `nucleo-l552ze-q` PASS

- `test_output.txt` PASS

2023-09-05 08:00 UTC, MrKevinWeiss commented
### Apps tests

tests/sys/shell

### Boards

- `nucleo-l552ze-q` PASS

2023-09-05 08:07 UTC, MrKevinWeiss commented
### Apps tests

tests/sys/shell

### Boards

- `nucleo-l552ze-q` PASS

2023-09-05 08:08 UTC, MrKevinWeiss commented
### Apps tests

tests/sys/shell

### Boards

- `nucleo-l552ze-q` PASS

2023-09-05 08:19 UTC, MrKevinWeiss commented
### Apps tests

tests/sys/shell

### Boards

- `nucleo-l552ze-q` PASS

2023-09-05 08:25 UTC, MrKevinWeiss commented
### Apps tests

tests/sys/shell

### Boards

- `nucleo-l552ze-q` PASS

2023-09-05 08:28 UTC, MrKevinWeiss commented
### Apps tests

tests/sys/shell

### Boards

- `nucleo-l552ze-q` FAIL
<details>

Failures during test.flash:
- [tests/sys/shell](tests/sys/shell/test.flash.failed)

</details>

2023-09-05 10:47 UTC, Teufelchen1 approved these changes

2023-09-05 10:54 UTC, Teufelchen1 commented
> The first question would be, is this a good way to preserve the hashes, by namespacing the `hashes` folder, or should I keep the hashes in the hashes next to the results, for example, `<results_base>/<board>/<app_dir>/test-input-hash.sha1` and carefully remove the remove everything but the hashes during the typical clean.
> 

I think namespacing is fine. I would rather have a different folder than messing with clean. I would be confused when I clean something and some arbitrary hashes remain.

> The second question would be to add a command (arg flag) to clean the hashes since they will persist until either they are manually removed or the results directory changes.

Hm voting against that. If you don't care about the hashes, don't pass `-c` to the tool, done. I do not see a use-case for deleting the hashes otherwise?


On a site note, this tool suffers from the common RIOT issue of not being exposed to user. Ideally, this PR would add a change to a handbook somewhere to explain its abilities to future RIOT developers...

2023-09-06 15:36 UTC, MrKevinWeiss commented
> On a site note, this tool suffers from the common RIOT issue of not being exposed to user. Ideally, this PR would add a change to a handbook somewhere to explain its abilities to future RIOT developers...

True, maybe an fairly obvious entrypoint in the docs for all the tools, why solve this problem when you can try to tackle all the problems.

2023-10-27 12:04 UTC, benpicco commented
bors merge

2023-10-27 14:33 UTC, benpicco commented
bors merge

2023-11-01 14:03 UTC, MrKevinWeiss commented
bors merge

2023-11-01 14:13 UTC, MrKevinWeiss commented
I am starting to think that it is me...

2023-11-04 17:44 UTC, benpicco commented
bors merge

2023-11-07 08:35 UTC, MrKevinWeiss commented
It was just a copy pasta error (`RIOT_TEST_RIOT_TEST_HASH_DIR` instead of `RIOT_TEST_HASH_DIR`).  Let's see if it is happy now.

2024-02-01 18:09 UTC, merged

2024-02-06 09:50 UTC, MrKevinWeiss commented
Thanks!