Makefile.include: Generate lst file using objdump
RIOT-OS/RIOT pull request #19745
Opened 2023-06-19 18:53 UTC by nandojve

### Contribution description

The MAP file does not provide all information necessary to do a full analize of generated code. This automatically generate the LST file with all relavant C and ASM code to help inspect code generated.

### Testing procedure

This was tested using AVR and Cortex-M toolchains.

2023-06-20 09:04 UTC, bergzand requested changes

2023-06-20 09:04 UTC, bergzand commented on Makefile.include
> +	$(Q)$(OBJDUMP) -DfFhlpSw $< > $@
Mind using the long  form argument form here? No need to keep this as short as possible and force the reader to look up the arguments.

2023-06-20 09:08 UTC, bergzand commented on Makefile.include
> +	$(Q)$(OBJDUMP) -DfFhlpSw $< > $@
I think this is the long form of all arguments:
```suggestion
	$(Q)$(OBJDUMP) --disassemble-all --file-headers --file-offsets --section-headers --line-numbers --private-headers --source --wide $< > $@
```

2023-06-20 14:11 UTC, bergzand approved these changes
Ack

2023-06-23 18:15 UTC, nandojve commented
ping

2023-06-23 18:35 UTC, maribu commented
bors merge

2023-06-27 18:04 UTC, nandojve commented
There is an issue with objdump for xtensa. It stay on a infinite loop generating the LST file.

2023-06-28 12:58 UTC, nandojve commented
Hi @maribu , can you try again if the change is fine?

2023-06-29 12:41 UTC, maribu approved these changes
lgtm. I assume that the objdump call can have some impact on the CI time and won't be useful there, so let's only create it in local builds.

Please squash right away and feel free to kick bors afterwards

2023-06-29 12:41 UTC, maribu commented on Makefile.include
> +endif
```suggestion
BUILD_FILES += $(ELFFILE) $(BINFILE) $(FLASHFILE) $(HASHFILE)

# when not in CI, aid developers in debugging the firmware with a full memory layout
# and disassembly provided by the lst file:
ifneq ($(RIOT_CI_BUILD),1)
  # as of now, the xtensa tools cannot create lst files
  ifeq (,$(findstring xtensa,$(PREFIX)))
    BUILD_FILES += $(LSTFILE)
  endif
endif
```

2023-06-29 19:07 UTC, merged