release-notes.txt: add 2023.07 release notes
RIOT-OS/RIOT pull request #19857
Opened 2023-08-02 12:10 UTC by benpicco

### Contribution description
This are the release notes for the 2023.07 Release. Please give it a look and make sure that your work in the last 3 months is present here.

### Testing procedure
- Read the document

### Issues/PRs references

2023-08-03 04:56 UTC, gschorcht requested changes

2023-08-03 04:56 UTC, gschorcht commented on release-notes.txt
> ++ drivers: add support for MTDs emulated in RAM (#19443)
```suggestion
+ drivers/mtd: add support for MTDs emulated in RAM (#19443)
+ drivers/mtd_default: add external declarations for mtd* (#19538)
```

2023-08-03 05:32 UTC, aabadie reviewed
Some initial comments in the generated list of PRs/issues

2023-08-03 05:32 UTC, aabadie commented on release-notes.txt
> +* tests/drivers: move all driver tests into own folder (#19435)
All `tests:` below should move to the Testing section.

2023-08-03 05:32 UTC, aabadie commented on release-notes.txt
> +* tests: move all periph applications to their own periphs/ folder (#19552)
All `tests:` and `treewide:` entries below should move to the Testing section

2023-08-03 05:32 UTC, aabadie commented on release-notes.txt
> ++ release-notes.txt: add 2023.04 release notes (#19503)
I think this should be dropped.

2023-08-03 05:32 UTC, aabadie commented on release-notes.txt
> +Uncategorized
If there are uncategorized itmes, it means some labels were missing. This section should not show up in the notes.

2023-08-03 05:32 UTC, aabadie commented on release-notes.txt
> +Deprecations
No deprecation, so just remove (something is missing in the script it seems)

2023-08-03 05:32 UTC, aabadie commented on release-notes.txt
> +* 2023.04 release bug tracking (#19469)
This should not show up in the notes

2023-08-07 14:45 UTC, gschorcht approved these changes
Looks good from my point of view, so 1 ACK from my side. Needs squashing of course.

2023-08-09 09:15 UTC, MrKevinWeiss reviewed
Just the few small things then I would ack.

2023-08-09 09:15 UTC, MrKevinWeiss commented on release-notes.txt
> +  whitespaces… (#19775)
```suggestion
```

2023-08-09 09:15 UTC, MrKevinWeiss commented on release-notes.txt
> +* treewide: fix typos and false positives found by codespell (#19528)
```suggestion
```

2023-08-09 10:26 UTC, benpicco commented
bors merge

2023-08-09 10:50 UTC, merged

2023-08-09 10:52 UTC, benpicco commented
Thank you!