coap: create typedef for CoAP methods
RIOT-OS/RIOT pull request #20003
Opened 2023-10-20 11:53 UTC by benpicco

### Contribution description

Avoid confusion between `COAP_PUT` and `COAP_METHOD_PUT` by creating a type for the latter.

### Testing procedure

### Issues/PRs references

2023-10-26 08:15 UTC, bergzand requested changes

2023-10-26 08:15 UTC, bergzand commented on sys/include/net/coap.h
> +    COAP_METHOD_IPATCH,             /**< iPATCH request (RFC 8132) */
I would prefer to see these all get a number explicitly assigned in the enum, to hint to the reader that the exact value of the enum matters

2023-11-02 10:56 UTC, bergzand approved these changes
Ack

2023-11-02 11:01 UTC, benpicco commented
bors merge

2023-11-02 15:49 UTC, merged