boards/e180-zg120b-tb: Document correct pin mapping
RIOT-OS/RIOT pull request #20263
Opened 2024-01-16 11:32 UTC by maribu

### Contribution description

Revision 1.0 of the board has an incorrect pin labeling on the silkscreen, presumably because the board was initially developed for a different E180 module and the silkscreen was not updated when populated with a different E180 module.

It is very likely that if newer revisions of the test board get produced, they will use the same very systematical routing as revision 1.0 and only the silkscreen labeling will be fixed. Hence, documenting the correct pin mapping will be useful even for newer revisions.

### Testing procedure

The pins on the header not routed to an NC pin on the module can be identified using https://github.com/RIOT-OS/RIOT/pull/20253 and the remaining can be traced with a multi-meter.

Note: The routing is pretty systematically and the pattern is quite obvious (only pin 1, the ANT pin, is not routed). This is how the module pins are routed to the header pins:

```
       23 | 22 | 21 | 20 | 19 | 18 | 17 | 16 | 16

24 | 25                                           14 | 13
26 | 27                                           12 | 11
28 | 29                                           10 | 9
30 | 31                                           8  | 7
32 | 33                                           6  | 5
34 | 35                                           4  | 3
36 | 37                                           2  | 2
```

With [the datasheet of the E180-ZG120B](https://www.ebyte.com/en/downpdf.aspx?id=842) module the pin mapping can therefore be easily checked.

### Issues/PRs references

Found while trying to understand why https://github.com/RIOT-OS/RIOT/pull/20236 didn't pass on this board. (Because I connected two pairs of GPIOs based on the incorrect silkscreen labels.)

2024-01-16 14:58 UTC, Teufelchen1 requested changes

2024-01-16 14:58 UTC, Teufelchen1 commented on boards/e180-zg120b-tb/doc.txt
> +@warning    At least for revision of the 10199-V1.0 of the test board most of the
Could you double check the grammar?

2024-01-18 12:53 UTC, maribu commented on boards/e180-zg120b-tb/doc.txt
> +@warning    At least for revision of the 10199-V1.0 of the test board most of the
Fixed and squashed

2024-01-18 13:12 UTC, Teufelchen1 approved these changes

2024-01-18 23:43 UTC, merged

2024-01-19 06:13 UTC, maribu commented
Thx :)