build system: add list of features for documentation and sanity checking
RIOT-OS/RIOT pull request #20366
Opened 2024-02-09 21:43 UTC by maribu

### Contribution description

This PR adds a `features.yaml` file as machine readable but easy to edit format that lists, groups, and documents all features ("feature" as in the the build system entity) in RIOT. A small python script generates a Makefile for and markdown file from that.

The Makefile is used to check if all features provided and requested are actually valid names or typos.

The Markdown file is used by Doxygen to generation a documentation page containing all features.

### Testing procedure

1. Try requesting or providing a non-existing feature. A build for an app+board combo that contains a feature provided or requested that does not exist should fail. (Note: A hard dependency on a non-existing feature will already fail in `master`, as a non-existing feature is never provided. An optional dependency to a non-existing feature would go unnoticed in `master`.)
2. Check the generated documentation

### Issues/PRs references

None

2024-02-09 21:46 UTC, maribu commented
This also needs some documentation. The quick guide is:

1. Edit `features.yaml` (in the root of the repo)
2. Run `make generate-features` (in the root of the repo)
3. Run `make doc` (in the root of the repo)

2024-02-10 22:08 UTC, maribu reviewed
CI comments

2024-02-10 22:08 UTC, maribu commented on doc/doxygen/src/feature_list.md
> +| `esp_wifi_enterprise`             | The ESP WiFi inteface supports WPA2 enterprise mode.                          |
```suggestion
| `esp_wifi_enterprise`             | The ESP WiFi interface supports WPA2 enterprise mode.                         |
```

2024-02-10 22:08 UTC, maribu commented on doc/doxygen/src/feature_list.md
> +Theses features indicate compatibility with a specific form factor, e.g. Arduino UNO or Adafruit Feather
```suggestion
These features indicate compatibility with a specific form factor, e.g. Arduino UNO or Adafruit Feather
```

2024-02-10 22:08 UTC, maribu commented on doc/doxygen/src/feature_list.md
> +# Bluetooth Low Engery Features
```suggestion
# Bluetooth Low Energy Features
```

2024-02-10 22:08 UTC, maribu commented on features.yaml
> +          The ESP WiFi inteface supports WPA2 enterprise mode.
```suggestion
          The ESP WiFi interface supports WPA2 enterprise mode.
```

2024-02-10 22:08 UTC, maribu commented on features.yaml
> +    help: Theses features indicate compatibility with a specific form factor,
```suggestion
    help: These features indicate compatibility with a specific form factor,
```

2024-02-10 22:08 UTC, maribu commented on features.yaml
> +Bluetooth Low Engery Features:
```suggestion
Bluetooth Low Energy Features:
```

2024-02-10 22:08 UTC, maribu commented on features.yaml
> +
```suggestion
```

2024-02-12 10:07 UTC, mguetschow commented
> This also needs some documentation. The quick guide is:
> 
>     1. Edit `features.yaml` (in the root of the repo)
> 
>     2. Run `make generate-features` (in the root of the repo)
> 
>     3. Run `make doc` (in the root of the repo)

Would it make sense to have `doc` depend on `generate-features` then? And we probably should document that workflow right in `features.yaml` to prevent people changing that without running `make generate-features` afterwards (does YAML even have comments?).

2024-02-12 10:11 UTC, mguetschow requested changes
Great work, that's a big step towards better documentation!

Did you write all the descriptions anew or did you take them from Kconfig files? If the latter is the case, we have to be careful of having several sources of truth in the tree and should converge to one eventually. Probably worth discussing at the VMA next week (and maybe wait with this PR until then?).

Some nit's below.

2024-02-12 10:14 UTC, maribu commented
> This also needs some documentation.

I added the missing documentation now

2024-02-12 10:22 UTC, maribu commented on makefiles/dependency_resolution.inc.mk
> +  # Detect provided / used / optional features that do not exist
Yes, indeed. I added this except for `FEATURES_USED`, as this is in intersection of `FEAUTRES_PROVIDED` and the other. So if it is not in any of these super sets, it won't be in the intersection.

2024-02-12 11:14 UTC, maribu commented
> Did you write all the descriptions anew or did you take them from Kconfig files?

A bit of both. The KConfig files did not have the grouping and since we disabled the feature check in the CI has started to bit-rot.

> If the latter is the case, we have to be careful of having several sources of truth in the tree and should converge to one eventually. Probably worth discussing at the VMA next week (and maybe wait with this PR until then?).

We did so last VMA: https://forum.riot-os.org/t/virtual-maintainer-assembly-vma-2023-11/4058/6

There was a bit of misunderstanding whether we drop all of KConfig or just the dependency (e.g. features and modules modeling). But in either case, the KConfig features are just a legacy as of now and this tries to salvage what I can and wire this back up into the CI.

2024-02-12 11:37 UTC, maribu commented
> Would it make sense to have `doc` depend on `generate-features` then?

I've added calling the script to generate the markdown file to `make doc`.

Note: The target `make generate-features` is still there and will no only create the Makefile. The reason I don't like to add this to very build is CI time. I added a test to `static-test` that will check if `features_existing.inc.mk` is still up to date and fail if not. That is not super elegant, but it reduced the CI overhead a lot and should just work.

2024-02-12 11:46 UTC, maribu commented
May I squash?

2024-02-12 13:34 UTC, MrKevinWeiss submitted a review, later dismissed
Do you mind waiting until tomorrow so I can take a quick look?  If it is urgent then you may dismiss.

2024-02-12 14:03 UTC, maribu commented
> Do you mind waiting until tomorrow so I can take a quick look? If it is urgent then you may dismiss.

No problem. There are still some open questions to be discussed anyway.

2024-02-13 10:04 UTC, MrKevinWeiss reviewed
Really nice that you are working on this...

Given the constraints (ie. grouping/nesting) probably using just make would not be so nice... maybe one can use wildcards and namespaces etc. but make would not be the best technology for that.

With kconfig, we can, theoretically nest with `menu` but extraction and manipulation of that data would not be as simple as loading a yaml file.

The only thing I would say about the yaml structure would be something like:
```yaml
- title: Architecture Features
  help: These indicate architecture features, such as word size of the CPU,
        supported instruction sets and so on. All architecture features provided
        by a given board will always be used, e.g. an 8-bit CPU cannot just stop
        being an 8-bit CPU on request.
  features:
    arch_8bit:
      CPU has a 8-bits architecture
    arch_16bit:
      CPU has a 16-bits architecture

- title: CPU Features
  help: These features are related to CPU capabilities or just used to
        indicated which CPU family is used.
  groups:
    - title: CPU Capabilities
      help: These correspond to features/capabilities provided by certain CPUs
      features:
        generic_cpu_feature:
          A generic CPU feature that is not specific to any CPU family.
      groups:
        - title: Cortex M Specific Features
          help: These features are only available on (some) ARM Cortex M MCUs
          features:
            cpu_check_address: The @ref cpu_check_address can be used to check if
                              accessing a given address would cause a bus fault.
            cortexm_svc:
              ARM Cortex-M Supervisor Calls are available.
        - title: nRF Capabilities
          help: These features are only available on (some) nordic nRF MCUs
          features:
            vdd_lc_filter_reg1:
              An LC filter for use with the internal DC/DC converter is
              present. If this is the case, the DC/DC converter is used over the
              LDO regulator for improved power efficiency.
            vdd_lc_filter_reg0:
              The MCU supports a high voltage supply via an two-stage regulator
              and the board has an LC filter required for using the two-stage
              DC/DC converter. This enables the two-stage DC/DC converter.
```

Though this does not prevent matching titles (I don't expect that to be an issue though).

I would wait for the VMA and maybe just get a consensus on introducing a new structure but I won't block it if people really want it in.

2024-02-20 12:25 UTC, chrysn reviewed
As requested in https://github.com/RIOT-OS/RIOT/issues/20393, it would be practical to link from the feature to supported boards. https://github.com/RIOT-OS/RIOT/pull/20395 has the infrastructure for obtaining that information (which is currently also generated in the `generate-features` target). To be useful, such lists should make use of board metadata (so that an output can be "all STM32 boards" where applicable), and possibly be collapsed (like, listing 3 and an HTML summary that tells how many there are and expands to the full litany). Given the interdependencies, I suggest not doing this here, but getting this merged and then building on it.

This looks good to me from a high-level perspective (haven't gone through every detail yet, trusting one of those two who have will given a more well-founded ACK that I could give). @mguetschow, have your concerns been addressed?

2024-02-21 12:23 UTC, mguetschow approved these changes
Since we agreed on going forward with this approach for feature documentation at today's VMA, I give an ACK on the implementation as is. As for the specific format, maybe you want to consider @MrKevinWeiss proposal to have fixed keys (moving the title to the sub-structure)?

I do think that the now duplicated information in the Kconfig should be removed in a timely fashion, if not in this PR, then in a follow-up. In the latter case, let's open an issue for it to keep it on the list (maybe you can directly give some pointers as to where you've extracted the information from).

2024-02-21 13:06 UTC, kaspar030 commented
> I'd vote for that, too. My main reason would be that it's easier to represent in Rust :). ... laze uses that scheme, too.

I'd even go further:

```
groups:
- title: CPU Features
  help: These features are related to CPU capabilities or just used to
        indicated which CPU family is used.
  groups:
    - title: CPU Capabilities
      help: These correspond to features/capabilities provided by certain CPUs
      features:
        - name: generic_cpu_feature
          help: A generic CPU feature that is not specific to any CPU family.
```

This maps cleanly to sth like:

```Rust
struct FeatureYaml {
  groups: Vec<Group>,
}

struct Group {
  name: String,
  help: String,
  groups: Vec<Group>,
  features: Vec<Feature>,
}

struct Feature {
 name: String,
 help: String,
}
```

While not using the yaml map key as name and yaml map value as text gives up the free uniqueness checks, in practice that's trivial to add. And having explicit fields for e.g., "name" and "help" (instead of directly using key&value) allows adding fields.

2024-02-23 14:03 UTC, maribu commented
Rebased on top of https://github.com/RIOT-OS/RIOT/pull/20408 to pass the CI, and squashed.

2024-02-25 15:36 UTC, chrysn commented
There's an implementation detail that could yet be improved but could also turn out to be a very deep time sink hole: Instead of (ab)using make with non-file-name targets to regenerate files, we could embrace make and use it to ensure that whenever the generated features_existing.inc.mk is out of date, it gets rebuilt. The reason I think this may be a huge time sink is that that could interact badly with having the file checked in, and the alternative to not having the file checked in is having a post-checkout step that generates it before forking off into thousands of build tasks, which is yet again complicated. So let's not slow things down here with that.

Given there is an ACK and that everything looks discussed and ready, pushing the button.

2024-02-25 17:21 UTC, merged

2024-02-25 19:45 UTC, maribu commented
Yeah! Thx :)

2024-02-26 15:42 UTC, benpicco commented on features.yaml
> +      help: The Flashpage peripheral is of the Read While Write.
I still don't know what that means :smile:

2024-02-26 16:06 UTC, chrysn commented
These docs are not new in this PR -- could you open an issue for clarification and assign recent contributors (and PR reviewers) of that feature?