[WIP]doc: Add guide for dev setup on Windows
RIOT-OS/RIOT pull request #20426
Opened 2024-02-23 13:41 UTC by maribu

### Contribution description

This adds a detailed instruction on how to get a working development setup on Windows.

State

- [x] Installation of WSL/Ubuntu
- [x] Cloning RIOT + first steps
- [x] Installation of VS Code
- [x] Integration of VS Code to WSL + IntelliSense
- [x] Working and compiling from VS Code
- [ ] Working on real hardware via USB IP

### Testing procedure

[Check here](https://github.com/maribu/RIOT/tree/doc/getting-started/windows/doc/guides/setup-windows) for a rendering of the added README.md

### Issues/PRs references

https://github.com/RIOT-OS/RIOT/issues/20388

2024-02-23 16:43 UTC, dylad commented
@maribu Note that you can also use .exe directly from WSL so one can install JLinkExe.exe (for example) into windows, symlink the .exe binary to JLinkExe within WSL then use good old `make flash` from WSL console to flash a board. This could be an interesting alternative to USBIP.
Of course, it will only work if the tool has a Windows version of it.

2024-02-23 17:50 UTC, maribu commented
With USB-IP also `make term` works and it is actually quite straight forward. I just need to prepare the screen shots

2024-02-24 09:14 UTC, dylad commented
Let me know when the full tutorial is ready. I'll give it a try on my W10 laptop.

2024-02-26 14:22 UTC, maribu commented
Should be good now :)

2024-02-27 19:07 UTC, Teufelchen1 commented
Awesome! Please be patient for a couple of days, maybe one or two weeks. I'm drowning in work rn.

2024-02-27 19:38 UTC, dylad commented
Followed the whole tutorial. I was able to successfully flash `p-nucleo-wb55` and `nrf5340dk-app` on W10 with WSL2.

The only issue is with DAP programmer which rely on USB HID. This is not supported by the default WSL Linux Kernel.
For now, I suggest to add a note in the tutorial to warn users.
We can add a specific workaround (using edbg windows binary) in a followup PR. Maybe this will be fix in a future WSL release.

For now, I think this PR is already in good shape !

2024-02-28 08:28 UTC, maribu commented
Thanks. I added the info about USB HID programmers.

I do get why Microsoft disabled `CONFIG_USB_HIDDEV`, as users are not expected to forward their Mouse and Keyboard directly to WSL.

The thing is that HID devices are the only USB device class that works on Windows without any driver being installed. (Which also makes sense: Installing your Mouse and Keyboard driver without using a Mouse and Keyboard on Windows will be a challenge.)

Abusing HID as transport for debuggers only became popular because of the desire to have the smooth driver-less experience Linux users are familiar with also on Windows. It's quite ironic that this decision resulted in the experience now being less smooth for Windows users wanting to use RIOT.

2024-02-28 09:05 UTC, dylad requested changes
Spotted a typo in the newly added text.
You can squash directly.

2024-02-28 09:05 UTC, dylad commented on doc/guides/setup-windows/README.md
> +as transport do not work for know. The (non-conclusive) list of affected
```suggestion
as transport do not work for now. The (non-conclusive) list of affected
```

2024-02-28 09:58 UTC, dylad approved these changes
Looking good !

2024-02-28 10:02 UTC, merged

2024-02-28 12:46 UTC, maribu commented
Thx :)