pkg/tinydtls: enforce the default dtls user params to be configurable
RIOT-OS/RIOT pull request #20478
Opened 2024-03-18 16:26 UTC by mariemC

### Contribution description

Incorporating the tinydtls build package, this code addresses a failure encountered during the DTLS handshake between the client and the server. The issue arose from the client imposing default user parameters, which mandate setting extended master secret and renegotiation info to 1. However, not all servers support these extensions. To ensure greater flexibility, it's more appropriate to make these parameters user-configurable

### Testing procedure

I utilized the 'examples/gcoap_dtls' on a native environment for the client. However, for the server, I deployed it on my Ubuntu machine, which lacks support for these extensions
results when the extensions are set to 0:
````
2024-03-18 16:45:30,983 # RIOT native interrupts/signals initialized.
2024-03-18 16:45:30,984 # RIOT native board initialized.
2024-03-18 16:45:30,985 # RIOT native hardware initialization complete.
2024-03-18 16:45:30,985 # 
2024-03-18 16:45:30,986 # main(): This is RIOT! (Version: 2024.04-devel-390-ge5f033-Mariem/dtls_default_user_params_fix)
2024-03-18 16:45:30,987 # default credentials will be used
2024-03-18 16:45:30,987 # gcoap example app
2024-03-18 16:45:30,988 # All up, running the shell now
nib route add 7 :: fe80::58da:6eff:fe50:5b94re
2024-03-18 16:45:33,294 # nib route add 7 :: fe80::58da:6eff:fe50:5b94
coap get "[fe80::58da:6eff:fe50:5b94%7]" /.well-known/core
2024-03-18 16:45:34,715 # coap get "[fe80::58da:6eff:fe50:5b94%7]" /.well-known/core
2024-03-18 16:45:34,716 # gcoap_cli: sending msg ID 42940, 23 bytes
> 2024-03-18 16:45:34,774 # gcoap: response Success, code 2.05, 455 bytes
2024-03-18 16:45:34,776 # </fw>,</fw/1>;title="Retrieve a firmware update",</fw/1/d>,</fw/1/d/42>,</fw/1/m>,</fw/1/m/AAAAAA>,</fw/2>;title="Retrieve a firmware update, API version 2",</fw/2/d>,</fw/2/d/42>,</fw/2/m>,</fw/2/m/AAAAAA>,</t>,</t/1>;title="Retrieve system time in milliseconds since unix epoch",</din>,</din/1>;title="Data Record Input, version 1",</din/1/AAAAAA>,</cmd>,</cmd/1>;title="Retrieve commands for execution on the device",</cmd/1/AAAAAA>,</.well-known/core>

````
results when the extensions are set to 1:
```
2024-03-18 16:45:56,159 # main(): This is RIOT! (Version: 2024.04-devel-390-ge5f033-Mariem/dtls_default_user_params_fix)
2024-03-18 16:45:56,159 # default credentials will be used
2024-03-18 16:45:56,160 # gcoap example app
2024-03-18 16:45:56,160 # All up, running the shell now
nib route add 7 :: fe80::58da:6eff:fe50:5b94
2024-03-18 16:45:58,584 # nib route add 7 :: fe80::58da:6eff:fe50:5b94
coap get "[fe80::58da:6eff:fe50:5b94%7]" /.well-known/core
2024-03-18 16:46:00,738 # coap get "[fe80::58da:6eff:fe50:5b94%7]" /.well-known/core
2024-03-18 16:46:00,738 # gcoap_cli: sending msg ID 19650, 23 bytes
2024-03-18 16:46:00,745 # error in check_server_hello err: -552
2024-03-18 16:46:00,746 # error 0x0228 handling handshake packet of type: server_hello (2), state 8
```

2024-03-18 16:36 UTC, leandrolanzieri requested changes
Thanks for this. I think this should be better off as a tinydtls configuration. For this I'd suggest to contribute the introduction of macros upstream. If, for now, you still want to contribute the patch to RIOT, please check my other comment about making the macros generic.

2024-03-18 16:36 UTC, leandrolanzieri commented on pkg/tinydtls/patches/0001-build-pkg-tinydtls-make-the-usage-of-extended-master.patch
> ++  .force_renegotiation_info = SOCK_DTLS_FORCE_RENEGOTIATION_INFO,
If these are really optional, the macros should be exposed by the package and injected via CFLAGS (i.e., they shouldn't be RIOT-specific macros, definitely not coming only from `sock_dtls_types.h` which exists only on RIOT).

2024-03-19 12:35 UTC, benpicco commented
tinyDTLS is also usually pretty good with incorporating our changes upstream, so you might want to directly open a PR [in their repo](https://github.com/eclipse/tinydtls) to keep the patches to the pkg to a minimum.

2024-03-19 13:41 UTC, mariemC commented
I'll open a PR in tinydtls repo

2024-03-21 16:58 UTC, mariemC commented
I have opened a PR in tinydtls, and they have suggested to adjust the default params via get_user_params() cb.

2024-03-22 10:59 UTC, benpicco commented on sys/include/net/sock/dtls.h
> +#endif
```suggestion
#ifndef CONFIG_DTLS_FORCE_EXTENDED_MASTER_SECRET
#define CONFIG_DTLS_FORCE_EXTENDED_MASTER_SECRET 1
#endif

/**
 * @brief Force renegotiation info extension
 */
#ifndef CONFIG_DTLS_FORCE_RENEGOTIATION_INFO
#define CONFIG_DTLS_FORCE_RENEGOTIATION_INFO 1
#endif
```

for consistency

2024-03-22 12:42 UTC, benpicco approved these changes
Looks good to me

2024-03-26 16:20 UTC, kfessel commented
@leandrolanzieri please link

2024-03-27 02:15 UTC, merged