Fix/samd5x/correct extended msg send api
RIOT-OS/RIOT pull request #20640
Opened 2024-04-30 09:58 UTC by firas-hamdi

### Contribution description

The SAMD5x does send correctly the extended frames only when the user inputs a CAN ID in which the extended flag bit is set. To avoid this error, this PR sets the extended flag bit automatically by the driver when an extended frame ID (superior to the standard ID mask) is detected

### Testing procedure

Testing steps:

1.  the test app is tests/drivers/candev, target hardware same54-xpro, tool to analyse the CAN bus is PCAN_USB adapter
2. With master, try to send a message with ID 0x0CABCDEF by starting shell command send.
3. Using the candump command, you will see that the message was sent as a standard frame and not an extended one.
![image](https://github.com/RIOT-OS/RIOT/assets/53952217/901a01ec-c967-46b5-9cc4-99c18d5f3a05)
4. With this PR, reproduce step 2 and 3. You'll notice that extended frame was sent correctly.
![image](https://github.com/RIOT-OS/RIOT/assets/53952217/012cd60d-7b4c-4e97-96cd-9dbc884f49f4)

2024-04-30 13:14 UTC, kfessel commented
this auto magic is not consistent with other can_send

2024-04-30 13:15 UTC, kfessel requested changes
this auto magic is not consistent with other can_send

2024-04-30 13:28 UTC, kfessel commented
strangely the mcp2512 driver does this

stm32 driver filters the id if eff isn't set
esp can driver filters the id if eff isn't set

socket_can also likes the eff flag to be set if it is an extended frame

i think mcp2512 should be updated

2024-04-30 16:16 UTC, firas-hamdi commented
> this auto magic is not consistent with other can_send

I don't understand your comment. What are you referring to as auto magic? And this PR uses the send API of the CAN interface which is generic to all CAN controller drivers, so where is it not consistent with other can_send?

2024-04-30 16:32 UTC, firas-hamdi commented
> strangely the mcp2512 driver does this
> 
> stm32 driver filters the id if eff isn't set esp can driver filters the id if eff isn't set
> 
> socket_can also likes the eff flag to be set if it is an extended frame
> 
> i think mcp2512 should be updated instead of standardizing special behavior
> 
> 0x80000000000007FF and 0x00000000000007FF are not the same and neither are higher values
> 
> maybe a assert in DEVHELP mode that triggers when trying to send a frame with an id that does not fit into the id size is a better solution to make users of this interface aware of the eff flag that needs to be set, other wise they might send a frame at 0x0000000000000012 and it will be handled wrong since it is not an automagic eff frame.

That can be also an approach that I tried, to force the user to send CAN IDs with extended flag set. But it is very error prone, and an assert is not a solution because without Develhelp the system will work but wrong. E.g the case where the user wants to send back every extended frame that was received, the user here will have to set by himself the extended flag bit. I see this very error prone to be honest

2024-04-30 16:36 UTC, firas-hamdi commented
What about this approach, to avoid the case you mentioned
`if ((can_id & CAN_EFF_MASK) > CAN_SFF_MASK) 
{
     extended flag processing ==> Set extended flag bit;
 }
 else {
  standard flag bit ==> Clear extended flag bit to avoid the case of 0x80000000 considered as extended ID;
  }    
`

2024-04-30 19:55 UTC, kfessel commented
> > this auto magic is not consistent with other can_send
> 
> I don't understand your comment. What are you referring to as auto magic? And this PR uses the send API of the CAN interface which is generic to all CAN controller drivers, so where is it not consistent with other can_send?

other can drivers don't do this this PRs code is sometimes guessing that a certain id is 29bit but it can not allways succeed since 29 Bit ID may be smaller than 2048 -> it would guess it is a 11Bit Id which in that described cases is wrong 

this guessing is auto magic that might work for some time you don't send the very important low 29bit id message with the correct number of bits.

2024-04-30 20:10 UTC, kfessel commented
> > strangely the mcp2512 driver does this
> > stm32 driver filters the id if eff isn't set esp can driver filters the id if eff isn't set
> > socket_can also likes the eff flag to be set if it is an extended frame
> > i think mcp2512 should be updated instead of standardizing special behavior
> > 0x80000000000007FF and 0x00000000000007FF are not the same and neither are higher values
> > maybe a assert in DEVHELP mode that triggers when trying to send a frame with an id that does not fit into the id size is a better solution to make users of this interface aware of the eff flag that needs to be set, other wise they might send a frame at 0x0000000000000012 and it will be handled wrong since it is not an automagic eff frame.
> 
> That can be also an approach that I tried, to force the user to send CAN IDs with extended flag set when needed. But it is very error prone, and an assert is not a solution because without Develhelp the system will work but wrong. E.g the case where the user wants to send back every extended frame that was received, the user here will have to set by himself the extended flag bit. I see this very error prone to be honest.

If a user receives extended id frame they also receive the eff bit -> they should remember that an use said bit may just copy the id (which includes the eff bit). without the eff bit extended id bits would be data bits using them for id would just be wrong.
DEVHELP enables the developer to detect his mistake ( eg not remembering the eff-bit) they get an assert and fix their wrong code if you think it is likely that the developer does not enable devhelp you might also use assert or panic but malhandling of these bits (not setting them even though wanting a extended id) should never go near production.

Doing what this code does hides bugs for a very long time and makes them very likely to slip into production where they will cause bad failures

2024-04-30 20:13 UTC, kfessel commented
> What about this approach, to avoid the case you mentioned `if ((can_id & CAN_EFF_MASK) > CAN_SFF_MASK) { extended flag processing ==> Set extended flag bit; } else { standard flag bit ==> Clear extended flag bit to avoid the case of 0x80000000 considered as extended ID; } `

forcing the misbehavior isn't the solution,  0x80000000 is a valid extended id so is every thing to 0x800007ff, these id allready have the eff flag set

2024-05-02 06:25 UTC, firas-hamdi commented
> > What about this approach, to avoid the case you mentioned `if ((can_id & CAN_EFF_MASK) > CAN_SFF_MASK) { extended flag processing ==> Set extended flag bit; } else { standard flag bit ==> Clear extended flag bit to avoid the case of 0x80000000 considered as extended ID; } `
> 
> forcing the misbehavior isn't the solution, 0x80000000 is a valid extended id so is every thing to 0x800007ff, these id allready have the eff flag set.
> 
> or in other words id 0 to 2047 can be either 11 bit id or 29 bit id but the protocols on top will mostlikely handle them different

0x80000000 is not a valid extended ID as well as 0x800007FF. The max extended ID is 0x1FFFFFFF (which is the EFF_MASK). So if for example user inputs as ID 0x80000000, we will check just the 29 bits ID and compare it to the max standard ID (0x7FF which is SFF_MASK). This way we won't use the extended flag bit as an indicator, we will use the limits of the standarad/extended IDs.
The distinction between standard and extended frames is happening with setting/clearing the identifier extension bit in the CAN protocol (And this is happening from defining the frame in the message RAM in this driver), that's why IDs from 0x0 to 0x7FF can not be considered standard or extended: they are just valid standard IDs

2024-05-02 06:39 UTC, firas-hamdi commented
> > > strangely the mcp2512 driver does this
> > > stm32 driver filters the id if eff isn't set esp can driver filters the id if eff isn't set
> > > socket_can also likes the eff flag to be set if it is an extended frame
> > > i think mcp2512 should be updated instead of standardizing special behavior
> > > 0x80000000000007FF and 0x00000000000007FF are not the same and neither are higher values
> > > maybe a assert in DEVHELP mode that triggers when trying to send a frame with an id that does not fit into the id size is a better solution to make users of this interface aware of the eff flag that needs to be set, other wise they might send a frame at 0x0000000000000012 and it will be handled wrong since it is not an automagic eff frame.
> > 
> > 
> > That can be also an approach that I tried, to force the user to send CAN IDs with extended flag set when needed. But it is very error prone, and an assert is not a solution because without Develhelp the system will work but wrong. E.g the case where the user wants to send back every extended frame that was received, the user here will have to set by himself the extended flag bit. I see this very error prone to be honest.
> 
> If a user receives extended id frame they also receive the eff bit -> they should remember that an use said bit may just copy the id (which includes the eff bit). without the eff bit extended id bits would be data bits using them for id would just be wrong. DEVHELP enables the developer to detect his mistake ( eg not remembering the eff-bit) they get an assert and fix their wrong code if you think it is likely that the developer does not enable devhelp you might also use assert or panic but malhandling of these bits (not setting them even though wanting a extended id) should never go near production.
> 
> Doing what this code does hides bugs for a very long time and makes them very likely to slip into production where they will cause bad failures

The first part of your comment is so wrong. The extended flag bit is not received anyway and the user can not see that. The user will receive a frame stored in the message RAM and will check the extended flag bit in the message RAM (not the extended flag bit implemented in RIOT). So copying will not included the said bit.
I'm not saying that I'm totally against the approach of forcing the user to set the extended flag bit whenever the user wants to send an extended frame, but I see it very error prone and that can be avoidable by the driver

2024-05-02 06:46 UTC, kfessel commented
0x80000000 is not a valid extended ID as well as 0x800007FF are what you get when u have the eff flag set with these IDs 

eff-id  0x00000000 and eff-id  0x000007FF are valid eff ids and they are not the same as 
sff-is 0x000 and  sff-id 0x7ff

so to probally work with those ids you have to store the eff bit and and work with it 
this PR would hide not doing that if the ID is lager then 0x7ff -> it is masking programming errors.

2024-05-02 07:09 UTC, kfessel commented
> > > > strangely the mcp2512 driver does this
> > > > stm32 driver filters the id if eff isn't set esp can driver filters the id if eff isn't set
> > > > socket_can also likes the eff flag to be set if it is an extended frame
> > > > i think mcp2512 should be updated instead of standardizing special behavior
> > > > 0x80000000000007FF and 0x00000000000007FF are not the same and neither are higher values
> > > > maybe a assert in DEVHELP mode that triggers when trying to send a frame with an id that does not fit into the id size is a better solution to make users of this interface aware of the eff flag that needs to be set, other wise they might send a frame at 0x0000000000000012 and it will be handled wrong since it is not an automagic eff frame.
> > > 
> > > 
> > > That can be also an approach that I tried, to force the user to send CAN IDs with extended flag set when needed. But it is very error prone, and an assert is not a solution because without Develhelp the system will work but wrong. E.g the case where the user wants to send back every extended frame that was received, the user here will have to set by himself the extended flag bit. I see this very error prone to be honest.
> > 
> > 
> > If a user receives extended id frame they also receive the eff bit -> they should remember that an use said bit may just copy the id (which includes the eff bit). without the eff bit extended id bits would be data bits using them for id would just be wrong. DEVHELP enables the developer to detect his mistake ( eg not remembering the eff-bit) they get an assert and fix their wrong code if you think it is likely that the developer does not enable devhelp you might also use assert or panic but malhandling of these bits (not setting them even though wanting a extended id) should never go near production.
> > Doing what this code does hides bugs for a very long time and makes them very likely to slip into production where they will cause bad failures
> 
> The first part of your comment is so wrong. The extended flag bit is not received anyway and the user can not see that. The user will receive a frame stored in the message RAM and will check the extended flag bit in the message RAM (not the extended flag bit implemented in RIOT). So copying will not include the said bit implemented by RIOT. I'm not saying that I'm totally against the approach of forcing the user to set the extended flag bit whenever the user wants to send an extended frame, but I see it very error prone and that can be avoidable by the driver

manual of same54
```
39.9.2 Rx Buffer and FIFO Element

R0 Bit 30 - XTD: Extended Identifier
Signals to the Host whether the received frame has a standard or extended identifier.
```

if this driver is not forwarding this information you might refer to the author of this driver and may be fix that 

the stm32 driver s read-frame function does it 
https://github.com/RIOT-OS/RIOT/blob/a620a3c27fafb5444930f11131cdda7bf573e2d5/cpu/stm32/periph/can.c#L463

2024-05-02 07:22 UTC, firas-hamdi commented
> 0x80000000 is not a valid extended ID as well as 0x800007FF are what you get when u have the eff flag set with these IDs

No the only way to consider 0x0 as extended flag is by setting the extended flag bit in the message RAM of the CAN controller when sending a frame

> eff-id 0x00000000 and eff-id 0x000007FF are valid eff ids and they are not the same as sff-is 0x000 and sff-id 0x7ff
> 
That way we could consider all standard IDs as extended IDs and we set automatically the extended flag bit in the message RAM when sending messages. If padding was good in this case we would have just one standard CAN protocol supporting only one CAN frame type. What you're saying here is doable, but no so logic 

> so to probally work with those ids you have to store the eff bit and and work with it this PR would hide not doing that if the ID is lager then 0x7ff -> it is masking programming errors.

How is it programming errors? The standard ID is defined as 11-bit ID which means it has a maximum, if we overcome that maximum we need the extension. So if the user wants to send standard frame, it must be inferior to 0x1FF, else the driver knows it is an extended frame

2024-05-02 07:30 UTC, kfessel commented
> How is it programming errors? The standard ID is defined as 11-bit ID which means it has a maximum, if we overcome that maximum we need the extension. So if the user wants to send standard frame, it must be inferior to 0x1FF, else the driver knows it is an extended frame

but eff has no minimum ( aside from 0) -> you need to know if a fram is extended or not you can not decide this on the id without the ide/eff/ xtd bit

2024-05-02 07:31 UTC, firas-hamdi commented
> > > > > strangely the mcp2512 driver does this
> > > > > stm32 driver filters the id if eff isn't set esp can driver filters the id if eff isn't set
> > > > > socket_can also likes the eff flag to be set if it is an extended frame
> > > > > i think mcp2512 should be updated instead of standardizing special behavior
> > > > > 0x80000000000007FF and 0x00000000000007FF are not the same and neither are higher values
> > > > > maybe a assert in DEVHELP mode that triggers when trying to send a frame with an id that does not fit into the id size is a better solution to make users of this interface aware of the eff flag that needs to be set, other wise they might send a frame at 0x0000000000000012 and it will be handled wrong since it is not an automagic eff frame.
> > > > 
> > > > 
> > > > That can be also an approach that I tried, to force the user to send CAN IDs with extended flag set when needed. But it is very error prone, and an assert is not a solution because without Develhelp the system will work but wrong. E.g the case where the user wants to send back every extended frame that was received, the user here will have to set by himself the extended flag bit. I see this very error prone to be honest.
> > > 
> > > 
> > > If a user receives extended id frame they also receive the eff bit -> they should remember that an use said bit may just copy the id (which includes the eff bit). without the eff bit extended id bits would be data bits using them for id would just be wrong. DEVHELP enables the developer to detect his mistake ( eg not remembering the eff-bit) they get an assert and fix their wrong code if you think it is likely that the developer does not enable devhelp you might also use assert or panic but malhandling of these bits (not setting them even though wanting a extended id) should never go near production.
> > > Doing what this code does hides bugs for a very long time and makes them very likely to slip into production where they will cause bad failures
> > 
> > 
> > The first part of your comment is so wrong. The extended flag bit is not received anyway and the user can not see that. The user will receive a frame stored in the message RAM and will check the extended flag bit in the message RAM (not the extended flag bit implemented in RIOT). So copying will not include the said bit implemented by RIOT. I'm not saying that I'm totally against the approach of forcing the user to set the extended flag bit whenever the user wants to send an extended frame, but I see it very error prone and that can be avoidable by the driver
> 
> manual of same54
> 
> ```
> 39.9.2 Rx Buffer and FIFO Element
> 
> R0 Bit 30 - XTD: Extended Identifier
> Signals to the Host whether the received frame has a standard or extended identifier.
> ```
> 
That's what I told you. When speaking we need to make the distinguish between the extended flag bit by RIOT (bit 32 of canid_t) and the extended flag bit in the message RAM. The first one won't be detected by the user when doing CAN operations because it's out of range.

> if this driver is not forwarding this information you might refer to the author of this driver and may be fix that
> 
> the stm32 driver s read-frame function does it
> 
> https://github.com/RIOT-OS/RIOT/blob/a620a3c27fafb5444930f11131cdda7bf573e2d5/cpu/stm32/periph/can.c#L463

This will require from the user at later operations to discard that bit to process the frames.

2024-05-02 07:34 UTC, firas-hamdi commented
To make it clear, the point from this PR is to get the transmission API more abstract when it comes to sending extended frames, without asking the user to set the extended flag (32nd bit in canid_t) which is RIOT specific (A method by RIOT used to distinguish extended and standard frames, but not a CAN specific one).

2024-05-02 07:39 UTC, kfessel commented
> This will require from the user at later operations to discard that bit to process the frames.

as they are supposed to if they just want the ID and allready processed the eff bit, but if the want to answer or forward eff frame at id 0 to 2047 they have to set the eff bit again and so they have to for all othe eff frames

> To make it clear, the point from this PR is to get the transmission API more abstract when it comes to sending extended frames, without asking the user to set the extended flag (32nd bit in canid_t) which is RIOT specific (A method by RIOT used to distinguish extended and standard frames, but not a CAN specific one).

https://www.kernel.org/doc/html/latest/networking/can.html 

has the eff bit in the id

2024-05-02 07:45 UTC, kfessel commented
you can not reliable determine if an id is an extended one or not just by looking at the id -> you are guessing ( for ids over 2047 you are guessing correct (since the is not sff > 2047)) but for ids lower than 2048 you might guess wrong since you can not decide on the id -> you are hiding bugs that will bite later, you dont know when but dependinding on the layer you run above this ( application) they can be catastrophic.

2024-05-02 07:51 UTC, firas-hamdi commented
> > This will require from the user at later operations to discard that bit to process the frames.
> 
> as they are supposed to if they just want the ID and allready processed the eff bit, but if the want to answer or forward eff frame at id 0 to 2047 they have to set the eff bit again and so they have to for all othe eff frames
> 
And this is what I would like to avoid. Because when the user reads the CAN protocol and it says 29 bit IDs for extended frames, then when trying to send extended frames with 29 bits they will find that sent as standard ID (Although the user is applying correctly the CAN protocol). That's what I want to abstract.

> > To make it clear, the point from this PR is to get the transmission API more abstract when it comes to sending extended frames, without asking the user to set the extended flag (32nd bit in canid_t) which is RIOT specific (A method by RIOT used to distinguish extended and standard frames, but not a CAN specific one).
> 
> https://www.kernel.org/doc/html/latest/networking/can.html
> 
> has the eff bit in the id

I know, because RIOT CAN network stack is inspired from that, basically a copy paste, and nothing is wrong with that. I'm just talking about CAN protocol here, where the extended flag (the 32nd bit) is not existing and won't be seen in the CAN trace

2024-05-02 07:52 UTC, kfessel commented
also your statement of 29 Bit are superior is wrong (extended frame ID (superior to the standard ID mask))  1.003 is not a better number then 2 they just distinct from each other the second one fits nicely into a group that is countable infinite while the first might not unless u define a group that is N/1000

2024-05-02 07:56 UTC, kfessel commented
> I know, because RIOT CAN network stack is inspired from that, basically a copy paste, and nothing is wrong with that. I'm just talking about CAN protocol here, where the extended flag (the 32nd bit) is not existing and won't be seen in the CAN trace

the bit is called IDE it is on the wire(s) and if your tracing application is not showing it it is just lazy or may be the existence of that bit is hidden in the number of digits displayed to you 

for candump 

```
CAN IDs, masks and data content are given and expected in hexadecimal values.
When the can_id is 8 digits long the CAN_EFF_FLAG is set for 29 bit EFF format.
Without any given filter all data frames are received ('0:0' default filter).

```

2024-05-02 07:57 UTC, firas-hamdi commented
> you can not reliable determine if an id is an extended one or not just by looking at the id -> you are guessing ( for ids over 2047 you are guessing correct (since the is not sff > 2047)) but for ids lower than 2048 you might guess wrong since you can not decide on the id -> you are hiding bugs that will bite later, you dont know when but dependinding on the layer you run above this ( application) they can be catastrophic.

And the usage of the extended flag bit has shown also its consequences here. I'm putting myself in the shoes of a user that does know nothing about the CAN driver, goes and reads the CAN protocol and finds that extended frames are 29 bits (extension by 18 bits of the 11 bits identifiers, this is where I'm extracting the range). User tries to send 29 bit frame, but find just the wrong frame was sent on the bus because he didn't apply the extended flag bit set by RIOT (which is not a CAN protocol specific). I don't find that pleasant as user (That's why I called it error prone)

2024-05-02 08:12 UTC, kfessel commented
> > you can not reliable determine if an id is an extended one or not just by looking at the id -> you are guessing ( for ids over 2047 you are guessing correct (since the is not sff > 2047)) but for ids lower than 2048 you might guess wrong since you can not decide on the id -> you are hiding bugs that will bite later, you dont know when but dependinding on the layer you run above this ( application) they can be catastrophic.
> 
> And the usage of the extended flag bit has shown also its consequences here. I'm putting myself in the shoes of a user that does know nothing about the CAN driver, goes and reads the CAN protocol and finds that extended frames are 29 bits (extension by 18 bits of the 11 bits identifiers, this is where I'm extracting the range). User tries to send 29 bit frame, but find just the wrong frame was sent on the bus because he didn't apply the extended flag bit set by RIOT (which is not a CAN protocol specific). I don't find that pleasant as user (That's why I called it error prone)

and in that case they have to know that they need to set the eff bit as can requires it -> make an assert to help that user but do not do auto magic since this user might want to send eff id 123 later and the ide bit willnot be set automatically -> this will fail and the user created a bug deeply hidden in something very expensive.

you are probably not putting your self into the shoes of another user you likely did that mistake yourself 3 days ago and u searched for that bug a long time and you wish riot had you covered while doing that but it did not and now you are trying to get a automagic in that would have prevend that but you are not looking at how it should be (set the eff or xtd or ide bit if you want to send a eff frame )

but you are not seeing the complete picture can id with out that bit are not always identifiable. the can standard requires not sff capable devices to at least be able to recognize the eff bit ignore frames even though the rest of the id might have matched their filter -> this bit is an essential part that belongs to the id.

2024-05-02 08:16 UTC, kfessel requested changes
this should be considered closed *NO merge*

2024-05-02 08:52 UTC, firas-hamdi commented
> and in that case they have to know that they need to set the eff bit as can requires it -> make an assert to help that user but do not do auto magic since this user might want to send eff id 123 later and the ide bit willnot be set automatically -> this will fail and the user created a bug deeply hidden in something very expensive.
>
> you are probably not putting your self into the shoes of another user you likely did that mistake yourself 3 days ago and u searched for that bug a long time and you wish riot had you covered while doing that but it did not and now you are trying to get a automagic in that would have prevend that but you are not looking at how it should be (set the eff or xtd or ide bit if you want to send a eff frame )
>
EFF bit is set by RIOT, XTD bit set by the driver so they are not same bit we're talking about. IDE bit in CAN is another thing too, specific to the CAN protocol. Of course the case you mentioned occured, this is how you find bugs or see some usage concerns.
  
> but you are not seeing the complete picture can id with out that bit are not always identifiable. the can standard requires not sff capable devices to at least be able to recognize the eff bit ignore frames even though the rest of the id might have matched their filter -> this bit is an essential part that belongs to the id.

Essential part that belongs to the ID according to the CAN stack in RIOT, not in the CAN protocol.

2024-05-02 08:53 UTC, firas-hamdi commented
Closed PR

2024-05-02 08:53 UTC, closed without merging

2024-05-02 09:00 UTC, kfessel commented
> > and in that case they have to know that they need to set the eff bit as can requires it -> make an assert to help that user but do not do auto magic since this user might want to send eff id 123 later and the ide bit willnot be set automatically -> this will fail and the user created a bug deeply hidden in something very expensive.
> > you are probably not putting your self into the shoes of another user you likely did that mistake yourself 3 days ago and u searched for that bug a long time and you wish riot had you covered while doing that but it did not and now you are trying to get a automagic in that would have prevend that but you are not looking at how it should be (set the eff or xtd or ide bit if you want to send a eff frame )
> 
> EFF bit is set by RIOT, XTD bit set by the driver so they are not same bit we're talking about. IDE bit in CAN is another thing too, specific to the CAN protocol. Of course the case you mentioned occured, this is how you find bugs or see some usage concerns.
> 
> > but you are not seeing the complete picture can id with out that bit are not always identifiable. the can standard requires not sff capable devices to at least be able to recognize the eff bit ignore frames even though the rest of the id might have matched their filter -> this bit is an essential part that belongs to the id.
> 
> Essential part that belongs to the ID according to the CAN stack in RIOT, not in the CAN protocol.

it is an essential part of the can protocol and XTD EFF_FLAG and IDE are the same information just on different layers.

the XTD bit  needs to be set (or is received) in case of an eff frame
the EFF_FLAG  needs to be set (or is received) in case of an eff frame
the IDE needs to be  recessive (1) in case of an eff frame (dominant in case of an 11 Bit id)