doc/CONTRIBUTION.md: document mediation process
RIOT-OS/RIOT pull request #20648
Opened 2024-05-03 14:14 UTC by maribu

### Contribution description

As agreed upon in the weekly coordination meeting we want to set up a channel / tool / process to aid contributors to solve conflicts.

This is especially aimed to empower contributors to solve conflicts with maintainers, as we were unsure that the existing code of conduct violation mechanism is sufficient to address conflicts that do not involve a CoC violation.

### Testing procedure

- [ ] Wait for the infrastructure to contact mediators to be in place and check if the address matches
- [ ] Check if the wording is clear
- [ ] Check if the doc is easy to find
- [ ] Check if it is made clear that the mechanism is intended to be a constructive tool aimed at solving the conflict
    - specifically: it should be clear to all parties than invoking the mediation should be seen as "blame game"

### Issues/PRs references

None

2024-05-03 14:26 UTC, mguetschow requested changes, later dismissed
Thanks a lot for putting effort into this! LGTM on a first read, just one typo and a suggestion below.

2024-05-03 14:26 UTC, mguetschow commented on CONTRIBUTING.md
> +will be forwarded to a panel of mediators is consisting of trusted RIOT
```suggestion
will be forwarded to a panel of mediators consisting of trusted RIOT
```

2024-05-03 14:26 UTC, mguetschow commented on CONTRIBUTING.md
> +    - E.g. your PR is rejected/blocked for unjust or non-technical reasons
```suggestion
    - Your PR is rejected/blocked for unjust or non-technical reasons.
```

I would end all of those sentences with full stops.

2024-05-03 15:05 UTC, mguetschow commented on CONTRIBUTING.md
> +    - E.g. your PR is rejected/blocked for unjust or non-technical reasons
I think it would be more consistent to add full stops to all sentences ;-)

2025-10-30 21:18 UTC, crasbe commented
@AnnsAnns do you want to pick this up as a procrastination project? :)

2025-10-30 23:26 UTC, AnnsAnns commented
I mean is there even anything to do here? This looks pretty much mergeable aside from the email potentially not existing?

2025-10-30 23:37 UTC, crasbe commented
If you're happy, maybe we can poke @maribu to squash the commits and @mguetschow to dismiss the Change Request? :)

2025-11-01 14:44 UTC, crasbe approved these changes

2025-11-01 14:49 UTC, merged