drivers/periph_gpio: let gpio_read() return bool
RIOT-OS/RIOT pull request #20936
Opened 2024-10-22 19:52 UTC by maribu

### Contribution description

Since https://github.com/RIOT-OS/RIOT/pull/20935 gpio_write() uses a `bool` instead of an `int`. This does the same treatment for `gpio_read()`.

This does indeed add an instruction to `gpio_read()` implementations. However, users caring about an instruction more are better served with `gpio_ll_read()` anyway. And `gpio_read() == 1` is often seen in newcomer's code, which would now work as expected.

### Testing procedure

This should not cause any regressions.

I cannot find any way to use `int gpio_read()` that won't work with `bool gpio_read()` anymore at the top of my head.

### Issues/PRs references

Same that https://github.com/RIOT-OS/RIOT/pull/20935 did for `gpio_write()`, but for `gpio_read()`.

2024-10-22 19:57 UTC, dylad requested changes

2024-10-22 19:57 UTC, dylad commented on drivers/include/periph/gpio.h
> + * @retval              high    pin is HIGH
```suggestion
 * @retval              true    pin is HIGH
```

2024-10-23 11:24 UTC, maribu commented
See https://github.com/RIOT-OS/rust-riot-wrappers/pull/132

2024-10-24 07:21 UTC, dylad approved these changes
Changes look good to me.

2024-10-24 07:22 UTC, dylad commented
Don't forget to remove the extra commit :)

2024-10-24 08:04 UTC, maribu commented
> Don't forget to remove the extra commit :)

Done. But since this requires recently merged changes to the rust wrappers to work with both old and new `gpio_read()` signature, I updated the `riot-rust-wrappers` and added this as commit using:

```sh
for dir in $(dirname $(find . -name Cargo.lock)); do 
    pushd $dir
    cargo update riot-wrappers
    popd
done
```

2024-10-24 12:02 UTC, chrysn approved these changes
LGTM at a glance, and I checked the Rust changes to be really just what is needed here.

In general I softly prefer doing the Rust changes outside the breaking PR (so that not just the riot-wrappers' limited CI runs, but it gets a full murdock run), but the change is so small here that doing it in the breaking PR is just as fine.

2024-10-24 13:21 UTC, dylad commented
@benpicco Should this PR go into master ?

2024-10-25 00:06 UTC, merged

2024-10-25 05:13 UTC, maribu commented
Thx :)