cpu/nrf52/radio/nrf802154: fix beacon acceptance
RIOT-OS/RIOT pull request #20982
Opened 2024-11-13 10:43 UTC by Lukas-Luger

### Contribution description

The nrf802154_radio.c file implements a frame filter on the MAC sublayer as mentioned in IEEE 802.15.4-2020 in Section 6.7.2 Reception and rejection. For beacon frames (section e), it should check if source PAN ID matches the PAN ID of the device. This is currently not the case and beacon frames get filtered out.

This PR implements the PAN ID check, while also confirming that source PAN ID is present in the first place.

### Testing procedure

Tests provided in the first commit. (requires two nrf52 devices)

### Issues/PRs references

2024-11-20 14:10 UTC, crasbe commented
I tested the PR today and everything works as expected.

My only two remaining remarks are:
1) The beacon function in the test program is called `send`, which doesn't make it super obvious that it'll send a beacon. `bcnsnd` would follow the "scheme" set by `txtsnd` or `beaconsend`, which is a bit nicer to remember.
Maybe as a description you could write `Send an IEEE 802.15.4 beacon` instead of `sending Beacon`.

2) While you're at it, you could add a sentence to the `About` section in the README file to specify for which devices this test works. I first grabbed an nRF52DK with the nRF52832, which does not support IEEE 802.15.4.
Something like "Supported are for example nRF52840 based boards."

2025-01-22 10:05 UTC, mguetschow requested changes
Tested and confirmed to work locally.

Just some small nitpicks below.

@crasbe I think your two comments have been addressed, right?

2025-01-28 18:22 UTC, mguetschow approved these changes
Perfect, then please squash so we can merge!

2025-01-28 20:23 UTC, merged

2025-01-28 20:27 UTC, miri64 commented
Congratz on your first merged PR, @Lukas-Luger :tada: