core/msg: re-enable IRQs before printing for highlevel_stdio
RIOT-OS/RIOT pull request #21047
Opened 2024-11-26 20:34 UTC by mguetschow

### Contribution description

highlevel_stdio such as usb-cdc-acm seems to require IRQs to be enabled for printing, but `msg_queue_print()` currently prints with IRQs disabled. This PR fixes that by copying the message queue information to the stack before re-enabling IRQs.

### Testing procedure

`make -C tests/core/msg_queue_print BOARD=feather-nrf52840-sense flash test`

hangs on `master`, passes with this PR

Changes tested on  `native` and `seeedstudio-xiao-nrf52840`.

### Issues/PRs references

Encountered while testing for #20980.

2024-11-26 20:41 UTC, miri64 requested changes
There is output on `nrf52840dongle` now for this test, but compared to `master` on `native` the numbers appear to be random.

2024-11-26 20:44 UTC, maribu commented on core/msg.c
> +    msg_t msg_array[size];
VLAs are pretty bad.

IMO we should define a static max value. If the actual queue ends up larger, we can print the first `MSG_QUEUE_PRINT_MAX_MSGS` and then just `, ...`. That will probably be good enough for most use cases.

I think btw. that it is a good design choice to just always copy, rather than avoiding a few bytes of extra stack needed for other boards:

1. This will make stack overflows more constant and easier to detect
2. This is better for real time
3. Less maintenance burden

2024-11-26 21:07 UTC, mguetschow commented on core/msg.c
> +    msg_t msg_array[size];
Thanks for the quick feedback! I've used a statically allocated buffer now, makes the logic a bit more cumbersome though.

2024-11-26 21:09 UTC, miri64 approved these changes
Now it works. Please squash.

2024-11-26 22:48 UTC, maribu commented on core/msg.c
> +        msg_t *m = &msg_array[(first_msg + i) & mask];
I'm not sure it was clear what I meant above: This here could lead to a buffer overflow in case of `msg_array` is smaller than `size`, e.g. when the last the positions in the ring buffer in `thread->msg_queue` containing a message.

2024-11-27 10:20 UTC, benpicco commented on core/msg.c
> +#define MSG_QUEUE_PRINT_MAX 16U
```suggestion
#ifndef CONFIG_MSG_QUEUE_PRINT_MAX
#define CONFIG_MSG_QUEUE_PRINT_MAX 16U
#endif
```

makes it a bit easier to change this

2024-11-27 15:02 UTC, mguetschow commented on core/msg.c
> +    unsigned int max = MIN(size, MSG_QUEUE_PRINT_MAX);
Done now, please double-check :)

2024-11-27 15:03 UTC, mguetschow commented on core/msg.c
> +#define MSG_QUEUE_PRINT_MAX 16U
I know :see_no_evil: done now

2024-11-27 15:07 UTC, maribu approved these changes
The CI has a nitpick. Please squash at will

2024-11-27 15:07 UTC, mguetschow commented
I've changed the test to also check the msg_queue copying in other cases and it works at least on `native`, but please double-check.

2024-11-28 11:02 UTC, miri64 commented on core/msg.c
A nitpick by the CI
```suggestion
        memcpy(msg_array, &thread->msg_array[msg_idx_first],
               sizeof(msg_t) * (msg_count_print));
    }
    else {
        unsigned msg_count_from_start = MIN((unsigned)(msg_idx_last + 1),
                                            msg_count_print - msg_count_to_end);
        memcpy(&msg_array[0], &thread->msg_array[msg_idx_first],
               sizeof(msg_t) * msg_count_to_end);
        memcpy(&msg_array[msg_count_to_end], &thread->msg_array[0],
               sizeof(msg_t) * msg_count_from_start);
    }
    irq_restore(state);

```

2024-11-28 11:50 UTC, mguetschow commented on core/msg.c
Applied and squashed :)

2024-11-28 17:29 UTC, merged