boards/same51-curiosity-nano: add support for the board
RIOT-OS/RIOT pull request #21111
Opened 2024-12-25 23:45 UTC by benpicco

### Contribution description

The [SAM E51 Curiosity Nano](https://www.microchip.com/en-us/development-tool/ev76s68a) is a cheap evaluation board for the SAM E51 family of MCUs. This family is pretty much identical with the SAM E54 family, except that it does not feature an Ethernet peripheral.

It does however feature two CAN peripherals.

### Testing procedure

TBD

### Issues/PRs references

2024-12-26 08:42 UTC, dylad requested changes
It looks good at first glance.
Could you please add this family to `cpu/sam0_common/include/vendor/readme.md`  ? It would be good to know which `atpack` version you used here and if you had modified any of them.

2024-12-26 08:42 UTC, dylad commented on boards/same51-curiosity-nano/doc.txt
> +Note that on Linux, you will need libudev-dev package to be installed.
Do we really need this for openOCD ?
I know that's the case for EDBG but I'm not sure for openOCD.

2024-12-26 08:42 UTC, dylad commented on boards/same51-curiosity-nano/doc.txt
> +`PROGRAMMER=openocd make BOARD=same51-curiosity-nano -C tests/leds flash`
Either delete or say a word about EDBG instead.

2025-01-07 09:03 UTC, dylad commented
LGTM. 
Please squash.

2025-01-07 09:24 UTC, maribu commented
What about the I2C test? Just forgot to paste the result, or is it an open todo?

My board also arrived now, so I also could give it a spin.

2025-01-07 10:36 UTC, benpicco commented
I don't have a I2C device with me at the moment

2025-01-08 08:35 UTC, dylad commented
@maribu Do you want to give I2C a quick try for this board ?
Otherwise I think we can move this forward.

2025-01-08 10:30 UTC, maribu commented
I tested I2C with an SHT3x first and an BME280 aferwards.

```
2025-01-08 11:25:13,080 # saul read 2
2025-01-08 11:25:13,081 # [bmx280] _do_measurement: measurement data ready
2025-01-08 11:25:13,093 # Reading from #2 (bme280|SENSE_TEMP)
2025-01-08 11:25:13,093 # Data:	         20.60 °C
> saul read 3
2025-01-08 11:25:15,552 # saul read 3
2025-01-08 11:25:15,559 # [bmx280] _do_measurement: measurement data ready
2025-01-08 11:25:15,560 # Reading from #3 (bme280|SENSE_PRESS)
2025-01-08 11:25:15,564 # Data:	        9961e1 Pa
> saul read 4
2025-01-08 11:25:18,815 # saul read 4
2025-01-08 11:25:18,815 # [bmx280] _do_measurement: measurement data ready
2025-01-08 11:25:18,828 # Reading from #4 (bme280|SENSE_HUM)
2025-01-08 11:25:18,829 # Data:	         51.31 %
```

Interestingly, I failed to read from the SHT3x unless I set `ENABLE_DEBUG` to `1` in `sht3x.c`. That looked a lot like some race condition, but I cannot tell whether this is in the SHT3x driver of the I2C driver. In any case, I think the issue is not related to this PR.

2025-01-08 14:17 UTC, dylad approved these changes
ACK.

2025-01-08 16:13 UTC, dylad commented
CI catches an issue with wolfssl.
We need an extra entry into `pkg/wolfssl/include/user_settings.h` to add `#define _SAME51_AES_COMPONENT_`

2025-01-08 23:07 UTC, merged